taskforcesh/bullmq

- src/classes/job.ts
- src/test/test_job.ts
> Save job stacktrace on failure

- docs/gitbook/README.md
Fix syntax in code example, colon to semi-colon (`:` -> `;`)
> Docs: update quick start page

- src/classes/compat.ts
- src/classes/queue-events.ts
- src/test/test_compat.ts
> $ as default queue event id #76

- docs/gitbook/guide/jobs/fifo.md
Quick typo fix for FIFO page:
onn -> on
> docs: fix typo

- src/classes/worker.ts
- src/test/test_worker.ts
Fix #71 
Now, if the `moveToFailed` command fail (eg: because the lock is missing), it will  catch the error. The error will still be sent as a local event.
This situation happens if the lock is too short for a job. It may be nice to add a message to help users debug this error.
> The task finished after lock duration. Try increasing `lockDuration` or use sandbox to prevent this situation
> fix: don't fail a job when the worker already lost the lock

- docs/gitbook/README.md
- docs/gitbook/guide/architecture.md
- docs/gitbook/guide/connections.md
- docs/gitbook/guide/introduction.md
- docs/gitbook/guide/jobs/README.md
- docs/gitbook/guide/jobs/stalled.md
- docs/gitbook/guide/untitled.md
- docs/gitbook/what-is-bullmq.md
Hey!
I was reading the docs this evening and decided to do some minor changes 😅
> docs: minor improvements

- src/classes/job.ts
- src/classes/queue-getters.ts
- src/test/test_getters.ts
- src/test/test_job.ts
- src/test/test_worker.ts
Fixes: https://github.com/taskforcesh/bullmq/issues/130
> fix: modified QueueGetters.getJob and Job.fromId to also return null

- src/classes/queue-base.ts
- src/classes/queue-scheduler.ts
In addition to making name public, I also added `readonly`. I think this is correct.
Fixes GH-140.
> feat: made queue name publicly readable for #140

- src/classes/job.ts
Marked finishedOn and processedOn as nullable/optional
> fix(job): added nullable/optional properties

- src/classes/queue-base.ts
- src/classes/redis-connection.ts
- src/classes/worker.ts
Existing code doesn't seem to pass error event through in a right way.
> fix: error event is passed through

- package.json
- src/classes/child-pool.ts
- src/classes/compat.ts
- src/classes/queue-events.ts
- src/classes/queue-scheduler.ts
- src/interfaces/redis-streams.ts
- yarn.lock
resolves #198 by updating the ioredis version
fixes some typescript errors
> fix(typescript): fix typings, upgrade ioredis dependencies

- src/classes/child-pool.ts
Fix for the issue discussed [here](https://github.com/taskforcesh/bullmq/issues/229)
> Remove async for loop in child pool

- docs/gitbook/guide/retrying-failing-jobs.md
Took me some time to realize I need a QueueScheduler for retries to work, thought this may help people using the manual.
Thanks!
> Add a remark about scheduler for retries to work

- docs/gitbook/README.md
This PR adds instructions to install `bullmq` with npm
Closes #325
> docs: add instructions for npm install

- src/classes/worker.ts
- src/test/test_worker.ts
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#327: How to use moveToFailed and moveToCompleted](https://issuehunt.io/repos/162494199/issues/327)
---
</details>
> feat: add support for manually processing jobs fixes #327

- src/classes/redis-connection.ts
Silences a typescript warning when viewing the file.
> chore(redis-connection): add explicit promise type

- src/classes/timer-manager.ts
Typed map of timers instead of a plain object and type "any".
> refactor(timer-manager): use Map to store timers

- docs/gitbook/SUMMARY.md
- docs/gitbook/patterns/debounce-jobs.md
Hi,
This days, I have search to debounce job with same Id in queue to avoid run multiple time an heavy computation. I didn't found this function here. I have fork project to implement this before see that it's already implemented. So i have tried to add a little example to doc this functionality.
> docs: add doc for bebounce usecase

- src/classes/child-pool.ts
- src/utils.ts
Specified promise type to make TS 4.1 and 4.2 happy.
> Compatibility with TS 4.1.x and 4.2.x

- src/classes/scripts.ts
- src/commands/moveToDelayed-5.lua
- src/interfaces/jobs-options.ts
- src/test/test_flow.ts
- src/test/test_job.ts
- src/test/test_rate_limiter.ts
This PR is for making sure that a job is in active state before we move it to delayed
> Throw an error if job is not in active state when moveToDelayed

- src/interfaces/redis-options.ts
> Fix missing Redis Cluster types

- src/classes/worker.ts
- src/interfaces/worker-options.ts
- src/test/test_worker.ts
Closes https://github.com/taskforcesh/bullmq/issues/516
> feat: create option for non-blocking getNextJob

- docs/gitbook/guide/workers/sandboxed-processors.md
fixes https://github.com/taskforcesh/bullmq/issues/539
> docs: fix job type in sandbox-processors guide

- src/classes/flow-producer.ts
- src/classes/queue.ts
- src/test/test_bulk.ts
- src/test/test_flow.ts
- src/test/test_obliterate.ts
> Fix flowProducer process parent with children as empty array

- docs/gitbook/CHANGELOG.md
This PR adds those version messages that are missing
> Missing version messages in changelog

- src/classes/job.ts
- src/commands/moveToFinished-7.lua
- src/test/test_clean.ts
> Fix event parent stream

- src/classes/flow-producer.ts
- src/test/fixtures/fixture_processor_crash.js
Just like the queue exposes the client with the same method
> Feat expose client connection in flow-producer

- docs/gitbook/CHANGELOG.md
- src/classes/queue-getters.ts
- src/test/test_worker.ts
> Fix getWorkers

- src/classes/queue-scheduler.ts
- src/classes/worker.ts
- src/test/test_stalled_jobs.ts
- src/test/test_worker.ts
For now I added only 2 events, at least those that I could check from tests
> Fix QueueScheduler: adding initial event typing

- package.json
- src/classes/compat.ts
- src/classes/queue-scheduler.ts
- src/classes/queue.ts
- src/classes/worker.ts
- src/test/test_compat.ts
- src/test/test_connection.ts
- src/test/test_getters.ts
- src/test/test_worker.ts
- yarn.lock
In order to get ioredis up to date and some typo fixes
> Deps upgrade ioredis

- src/classes/backoffs.ts
- src/classes/worker.ts
> Fix worker: await for processing functions

- docs/gitbook/guide/events.md
- src/classes/worker.ts
> Feat add drained event typing on worker

- src/classes/worker.ts
- src/test/test_sandboxed_process.ts
> Fix worker: change active event typing

- src/commands/moveStalledJobsToWait-8.lua
> Fix stalled-jobs: move stalled jobs to wait in batches

- src/classes/repeat.ts
- src/test/test_repeat.ts
> Fix repeatable: validate endDate when adding next repeatable job

- src/classes/scripts.ts
- src/commands/moveToFinished-8.lua
- src/test/test_worker.ts
> Fix moveToFinished: remove stalled jobs when finishing

- docs/gitbook/changelog.md
- src/classes/flow-producer.ts
- src/classes/job.ts
- src/classes/scripts.ts
- src/test/test_job.ts
- src/utils.ts
The list of version are not being showed properly, it is about # in each version after 1.39.4
> Fix docs changelog style

- src/test/test_rate_limiter.ts
There is a flaky test that sometimes in github pipeline fails.
> Fix flaky test in rate limit

- .eslintignore
- docs/gitbook/changelog.md
This PR excludes changelog in order to not apply lint rules into this file
> Lint exclude changelog

- .gitignore
- src/classes/flow-producer.ts
- src/classes/job.ts
This pr adds some jsdoc sentences and fix some others
> Docs: apply jsdoc

- src/classes/queue-base.ts
- src/test/test_events.ts
> fix: protect emit calls with throw/catch

- .mocharc.js
- package.json
- src/mocha.setup.ts
- src/test/test_bulk.ts
- src/test/test_clean.ts
- src/test/test_compat.ts
- src/test/test_connection.ts
- src/test/test_delay.ts
- src/test/test_flow.ts
- src/test/test_job.ts
- src/test/test_rate_limiter.ts
- src/test/test_repeat.ts
- src/test/test_sandboxed_process.ts
In order to have a central place to add mocha configuration
> Add mocha setup file

- src/classes/queue-events.ts
- src/commands/addJob-8.lua
- src/test/test_events.ts
Add added event when a job is created by addJob script
> Feat(events): add added event when job is created

- docs/gitbook/changelog.md
- src/test/test_delay.ts
- src/test/test_events.ts
- src/test/test_flow.ts
- src/test/test_getters.ts
- src/test/test_worker.ts
Same as title, I'm checking my redis db and I'm seeing some keys that were not cleaned
> test: clean redis db after finishing test cases

- package.json
- src/classes/job.ts
- src/classes/scripts.ts
- src/commands/obliterate-2.lua
- src/test/test_repeat.ts
Also adding some missing typing
> test(repeat): restore test

- src/classes/queue-scheduler.ts
- src/interfaces/queue-scheduler-options.ts
- src/test/test_delay.ts
> feat(queue-scheduler): launch without launching process

- src/classes/worker.ts
- src/interfaces/worker-options.ts
- src/test/test_worker.ts
> feat(worker): launch without launching process

- src/test/test_flow.ts
> test(flow-producer): add test case using priority option

- src/classes/queue-events.ts
- src/classes/queue-keys.ts
- src/classes/queue.ts
- src/classes/redis-connection.ts
- src/classes/worker.ts
> fix(queue-events): duplicate connection

- src/classes/job.ts
- src/classes/queue-events.ts
- src/classes/redis-connection.ts
- src/commands/isFinished-3.lua
- src/test/test_job.ts
- src/test/test_rate_limiter.ts
> fix(is-finished): reject when missing job key

- src/classes/queue-base.ts
- src/classes/redis-connection.ts
- src/test/test_connection.ts
- src/test/test_rate_limiter.ts
ref https://github.com/OptimalBits/bull/pull/2152
> fix(connection): fail only if redis connection does not recover

- src/classes/queue-events.ts
- src/classes/redis-connection.ts
- src/utils.ts
This PR is for have error handler in utils to be reused
> refactor(utils): add handleError

- src/classes/flow-producer.ts
- src/test/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/762
> fix(flow-producer): use default prefix in add method

- docs/gitbook/guide/jobs/repeatable.md
Corrected bird's name & comparative adjective for repeatable frequency.
> Documentation quality: Language & typo corrections

- README.md
- docs/gitbook/guide/events.md
- docs/gitbook/guide/returning-job-data.md
- docs/gitbook/guide/workers.md
- docs/gitbook/guide/workers/README.md
> docs(events): update completed and failed events docs

- src/classes/scripts.ts
- src/test/test_job.ts
> fix(change-delay): add current time to delay

- README.md
add badge to be aware at first view that we are using semantic-release
> docs(readme): add semantic-release badge

- src/interfaces/flow-job.ts
fixes https://github.com/taskforcesh/bullmq/issues/851
> fix(flow): remove repeat option from children

- src/test/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/863
> test(worker): check finished value passed in completed event

- package.json
api documenter add extra files in dist directory, we don't need those files to be published
> chore(deps): apply rimraf to delete extra published files

- src/classes/redis-connection.ts
- src/commands/index.ts
- src/test/test_events.ts
That function will allow us to reuse the same includes in pro version
> feat(load-includes): export includes to be reused in extensions

- src/commands/cleanJobsInSet-2.lua
ref https://github.com/OptimalBits/bull/pull/2205
> fix(clean): use range values in lua script

- .github/workflows/coverage.yml
- src/utils.ts
- tsconfig.json
fixes https://github.com/taskforcesh/bullmq/issues/894
> fix(tsconfig): only include node types

- src/commands/moveStalledJobsToWait-8.lua
fixes https://github.com/taskforcesh/bullmq/issues/863
tests https://github.com/taskforcesh/bullmq-tests/pull/2
> fix(stalled): save finidhedOn when job stalled more than allowable limit

- src/classes/job.ts
- src/interfaces/jobs-options.ts
this is for trying defaultValue tag
> docs(job): use defaultValue tag

- src/classes/job.ts
- src/classes/queue-events.ts
- tests/test_pause.ts
- tests/test_script_loader.ts
ref https://rjzaworski.com/2019/10/event-emitters-in-typescript
> feat(queue-events): add better event typing

- package.json
- src/classes/child-pool.ts
- src/classes/worker.ts
- tsconfig-cjs.json
- tsconfig.json
Hopefully fixes https://github.com/taskforcesh/bullmq/issues/917
> feat: also export bullmq as an ESM

- package.json
> fix: copy lua files to correct location

- docs/gitbook/patterns/debounce-jobs.md
> Fix docs. Update debounce-jobs.md

- src/classes/redis-connection.ts
- src/classes/worker.ts
> fix(worker): fix undefined moveToActive

- docs/gitbook/SUMMARY.md
- docs/gitbook/patterns/throttle-jobs.md
> docs(throttle-jobs): fix definition in patterns

- src/classes/job.ts
- src/classes/queue-getters.ts
- src/classes/queue.ts
- src/classes/worker.ts
- tests/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/384
> feat(worker): reuse generic typing for jobs

- src/classes/scripts.ts
- src/commands/updateProgress-2.lua
- tests/test_job.ts
could fix https://github.com/taskforcesh/bullmq/issues/977
> fix(update-progress): throw error if job key is missing

- src/classes/worker.ts
- tests/fixtures/fixture_processor.cjs
- tests/test_clean.ts
- tests/test_sandboxed_process.ts
ref https://github.com/taskforcesh/bullmq/issues/463
> feat(sanboxed-process): support .cjs

- src/classes/job.ts
ref https://github.com/taskforcesh/bullmq/issues/134
> refactor(job): delete unnecessary jobId check in fromId

- src/classes/compat.ts
- src/classes/job.ts
- src/classes/queue-getters.ts
- src/classes/scripts.ts
- src/enums/error-code.enum.ts
- src/enums/index.ts
- src/index.ts
- src/types/index.ts
- src/types/job-type.ts
- src/types/job-types.ts
- tests/test_events.ts
fix https://github.com/taskforcesh/bullmq/issues/1006 https://github.com/taskforcesh/bullmq/issues/744
> feat(queue): add JobTypes for better typing

- src/commands/script-loader.ts
if the modules paths is empty don't loop through them fixes #1012
> dont loop through empty modules path

- src/classes/scripts.ts
- src/commands/moveToFinished-8.lua
- src/interfaces/index.ts
- src/interfaces/jobs-options.ts
- src/interfaces/keep-jobs.ts
- tests/test_compat.ts
- tests/test_worker.ts
> feat: add support for removeOn based on time

- src/classes/repeat.ts
- tests/test_repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/1020
> fix(repeat): consider immediately param

- tests/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/1015
> test: pass shared connection into Queue

- src/interfaces/flow-job.ts
ref https://github.com/taskforcesh/bullmq/issues/1034
> docs(flow-job): add description into flow-opts

- src/classes/queue-getters.ts
- tests/test_getters.ts
- tests/test_queue.ts
ref https://github.com/taskforcesh/bullmq/issues/1067
> feat(get-job-counts): add defaults

- src/classes/queue-getters.ts
- src/classes/queue-scheduler.ts
- tests/test_getters.ts
- tests/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/1075
> feat(queue-getters): add getQueueSchedulers

- src/commands/includes/moveJobFromWaitToActive.lua
- src/commands/moveToActive-8.lua
- src/commands/moveToFinished-8.lua
- tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/1094
> fix(move-to-finished): increment attemptsMade when moving job to active

- src/classes/redis-connection.ts
- tests/test_connection.ts
fixes https://github.com/taskforcesh/bullmq/issues/1087
> fix(connection): advertise that Upstash is not compatible with Bullmq

- src/classes/redis-connection.ts
https://github.com/taskforcesh/bullmq/issues/1101
> [Draft] fix upstash check

- src/commands/moveToActive-8.lua
- tests/test_rate_limiter.ts
fixes https://github.com/taskforcesh/bullmq/issues/1084
> fix(rate-limiter): move job to wait after retry when groupKey is missed

- src/utils.ts
fixes https://github.com/taskforcesh/bullmq/issues/1120
> fix(utils): fix proc.send type

- src/classes/scripts.ts
- src/classes/worker.ts
- src/commands/includes/moveJobFromWaitToActive.lua
- src/commands/moveToActive-8.lua
- src/commands/moveToFinished-9.lua
- tests/test_events.ts
fixes https://github.com/taskforcesh/bullmq/issues/1121 ref https://github.com/taskforcesh/bullmq/issues/1070
> fix(drained): emit event only once when worker is idle

- src/classes/queue-getters.ts
- tests/test_getters.ts
See https://github.com/taskforcesh/bullmq/issues/1112
The PR is splitted in 3 incremental commits. Each commit brings more changes, so you can choose what to merge or not.
First two commits should be safe to merge. 3rd commit improves consistency and should ensure that `getJobs` always returns the same count as `getJobsCount`, but it's more intrusive.
> Get jobs enhancements

- src/classes/index.ts
- tests/test_rate_limiter.ts
fixes https://github.com/taskforcesh/bullmq/issues/1125, ref #1129
> fix(master): do not export master file

- src/utils.ts
- tests/test_rate_limiter.ts
ref https://github.com/taskforcesh/bullmq/issues/1140
> fix(async-send): check send type

- package.json
- src/classes/repeat.ts
- src/interfaces/repeat-options.ts
- tests/test_repeat.ts
- yarn.lock
fixes https://github.com/taskforcesh/bullmq/issues/1147
> feat(cron-parser): upgrades version to 4.2.1

- src/classes/worker.ts
ref https://github.com/taskforcesh/bullmq/issues/1188
> feat(worker-listener): use generics in events

- src/utils.ts
fixes https://github.com/taskforcesh/bullmq/issues/1185, also to be backward compatible with bull api
> fix(worker): restore worker suffix to empty

- src/classes/queue-base.ts
- src/classes/queue-events.ts
- src/classes/queue-scheduler.ts
- src/classes/queue.ts
- src/classes/redis-connection.ts
- src/classes/worker.ts
- tests/test_clean.ts
- tests/test_delay.ts
- tests/test_events.ts
- tests/test_getters.ts
- tests/test_obliterate.ts
- tests/test_queue.ts
- tests/test_sandboxed_process.ts
- tests/test_worker.ts
fixes https://github.com/taskforcesh/bullmq/issues/1205
> fix(queue-base): emit close error when no closing

- src/classes/job.ts
- src/classes/worker.ts
- src/commands/includes/removeJobsByMaxAge.lua
- src/commands/includes/removeJobsByMaxCount.lua
- src/commands/moveStalledJobsToWait-8.lua
- src/commands/moveToFinished-12.lua
- tests/test_stalled_jobs.ts
fixes https://github.com/taskforcesh/bullmq/issues/1171
> Fix remove on fail stalled

- src/classes/queue-events.ts
- src/commands/removeRepeatable-2.lua
- tests/test_repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/1212
> fix(repeatable): emit removed event when removing

- src/classes/compat.ts
- src/classes/queue.ts
- src/classes/repeat.ts
- src/classes/scripts.ts
- src/commands/moveStalledJobsToWait-8.lua
- src/commands/removeRepeatable-2.lua
- tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/1235
> feat(remove-repeatable): return boolean depending on job existence

- src/classes/child-processor.ts
- src/classes/flow-producer.ts
- src/classes/queue.ts
- src/classes/redis-connection.ts
- src/classes/repeat.ts
- src/classes/scripts.ts
- src/utils.ts
- tests/test_clean.ts
ref https://github.com/taskforcesh/bullmq/pull/1246
fixes https://github.com/taskforcesh/bullmq/issues/1243
> fix(redis-connection): save cluster opts

- src/classes/worker.ts
- tests/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/22
> feat(worker): change the number of concurrent processes

- src/classes/job.ts
- src/classes/scripts.ts
- tests/test_worker.ts
> fix(job): save finishedOn attribute on instance

- src/classes/job.ts
- tests/test_sandboxed_process.ts
fixes https://github.com/taskforcesh/bullmq/issues/1317
> fix(sandboxed-process): consider Unrecoverable error

- src/classes/flow-producer.ts
- tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/1334
> fix(get-flow): consider groupKey

- src/classes/child-processor.ts
> Fix Error [ERR_REQUIRE_ESM]

- renovate.json
as discussed in https://github.com/taskforcesh/bullmq/discussions/1348?notification_referrer_id=NT_kwDOAEcl3LI0MTE4Njg0OTc3OjQ2NjI3NDg#discussioncomment-3315218
> ci: add renovate configuration

- src/classes/child-processor.ts
Reverts taskforcesh/bullmq#1369
> fix: Revert "Fix Error [ERR_REQUIRE_ESM]"

- package.json
fix https://github.com/taskforcesh/bullmq/issues/917
> fix: revert "chore: allow esm imports through exports field"

- package.json
- src/classes/job.ts
- src/classes/queue-base.ts
- src/classes/scripts.ts
- src/commands/changeDelay-4.lua
- tests/test_job.ts
- yarn.lock
ref https://github.com/taskforcesh/bullmq/issues/1332
fixes https://github.com/taskforcesh/bullmq/issues/1160
> fix(job): update delay when changeDelay

- src/classes/child-processor.ts
- src/classes/sandbox.ts
- src/interfaces/parent-command.ts
- src/interfaces/sandboxed-job.ts
- tests/fixtures/fixture_processor_update.js
- tests/test_sandboxed_process.ts
ref https://github.com/taskforcesh/bullmq/issues/1415
> feat(sandbox): support update method

- src/classes/child-processor.ts
- src/interfaces/sandboxed-job.ts
- tests/fixtures/fixture_processor_update_progress.js
- tests/test_sandboxed_process.ts
BREAKING CHANGE: updateProgress should be used instead
> fix(sandbox): remove progress method

- src/classes/redis-connection.ts
- tests/test_connection.ts
BREAKING CHANGE: noeviction maxmemory-policy is the only option allowed
re #921
> fix(connection): throw error when no noeviction policy

- src/classes/queue-events.ts
- src/classes/redis-connection.ts
- src/commands/addJob-8.lua
- tests/test_connection.ts
- tests/test_events.ts
There were some missing breaking changes that should have gotten into 2.0 but by mistake were not there. Confronted between releasing a new 3.0 or a micro 2.0.1 I will go with the second choice since this was done right away after releasing 2.0.
> Missing breaking changes in 2.0

- src/classes/backoffs.ts
- src/classes/job.ts
- src/interfaces/advanced-options.ts
- src/types/backoff-strategy.ts
- src/types/index.ts
- tests/test_flow.ts
- tests/test_worker.ts
BREAKING CHANGE: object mapping is replaced by single function
> fix(backoff): handle backoff strategy as function

- src/classes/redis-connection.ts
- tests/test_connection.ts
fixes https://github.com/taskforcesh/bullmq/issues/1467
> fix(connection): validate array of strings in Cluster

- src/commands/includes/moveParentFromWaitingChildrenToFailed.lua
- tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/1469
> fix(fpof): send failed event

- src/classes/flow-producer.ts
- tests/test_flow.ts
ref https://github.com/taskforcesh/bullmq/issues/1480
> feat(flows): allow parent on root jobs in addBulk method

- src/commands/addJob-8.lua
- src/commands/includes/updateParentDepsIfNeeded.lua
- src/commands/moveToFinished-12.lua
- tests/test_flow.ts
ref https://github.com/taskforcesh/bullmq/issues/1036
> feat(flow): move parent to delayed when delay is provided

- src/classes/worker.ts
there is a test case that covers this case https://github.com/taskforcesh/bullmq/blob/master/tests/test_stalled_jobs.ts#L311-L377
ref https://github.com/taskforcesh/bullmq/issues/1495
> fix(worker): consider removed jobs in failed event

- src/classes/queue-getters.ts
- src/classes/worker.ts
- src/utils.ts
fixes https://github.com/taskforcesh/bullmq/issues/1574
> fix(worker): try catch setname call

- src/classes/child-processor.ts
- tests/fixtures/fixture_processor_missing_function.js
- tests/test_flow.ts
- tests/test_sandboxed_process.ts
fixes https://github.com/taskforcesh/bullmq/issues/1587
> fix(sandbox): throw error when no exported function

- src/classes/queue-getters.ts
- tests/test_getters.ts
ref https://github.com/taskforcesh/bullmq/issues/1532
> feat(queue): add getJobState method

- src/classes/redis-connection.ts
- tests/test_connection.ts
> fix(connection): throw exception if using keyPrefix in ioredis

- src/classes/worker.ts
- tests/test_delay.ts
fixes https://github.com/taskforcesh/bullmq/issues/1615
> fix(delayed): remove marker after being consumed

- docs/gitbook/guide/jobs/removing-job.md
- docs/gitbook/guide/jobs/repeatable.md
- src/classes/child-processor.ts
- src/classes/master.ts
- src/interfaces/child-message.ts
- src/utils.ts
- tests/fixtures/fixture_processor_fail.js
fixes https://github.com/taskforcesh/bullmq/issues/1414
> fix(error): remove global prototype toJSON

- docs/gitbook/guide/jobs/delayed.md
- docs/gitbook/guide/retrying-failing-jobs.md
- package.json
- tsconfig-cjs.json
- tsconfig.json
base on https://github.com/taskforcesh/bullmq/pull/1362
> build(types): build types only once

- src/classes/worker.ts
> fix: add a maximum block time

- docs/gitbook/guide/jobs/stalled.md
- docs/gitbook/guide/workers/graceful-shutdown.md
Hi, I'd like to send this PR to fix some typos and references.
> docs: fix typos

- src/classes/job.ts
- src/classes/scripts.ts
- src/commands/saveStacktrace-1.lua
ref https://github.com/taskforcesh/bullmq/issues/1676
> fix(job): check jobKey when saving stacktrace

- src/classes/worker.ts
- src/interfaces/flow-job.ts
- src/interfaces/redis-options.ts
fixes https://github.com/taskforcesh/bullmq/issues/1690
> fix(worker): failed event receives an optional job parameter

- src/commands/moveToFinished-12.lua
- tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/1752
> fix(flow): consider removing dependency on removeOnFail true

- docs/gitbook/SUMMARY.md
- docs/gitbook/guide/flows/adding-bulks.md
- docs/gitbook/guide/queues/adding-bulks.md
- tests/test_flow.ts
> docs(flow-producer): add usage of addBulk method

- src/classes/repeat.ts
- tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/165
> test(repeat): check delayed records are deleted

- docs/gitbook/guide/jobs/removing-job.md
- src/classes/flow-producer.ts
- src/commands/includes/removeParentDependencyKey.lua
- tests/test_clean.ts
- tests/test_flow.ts
- tests/test_repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/1778
> fix(flow): do not remove completed children results

- python/bullmq/event_emitter.py
- python/bullmq/job.py
- python/bullmq/queue.py
- python/bullmq/redis_connection.py
- python/bullmq/scripts.py
- python/bullmq/timer.py
- python/bullmq/worker.py
- python/requirements.txt
This PR updates all python docs comments to match the ones in the node version.
I had to format these files with the formatter in my vscode, but it should be the standard, so some lines have changed for this, for example a line has been added between two functions since by standard this should be the default formatting rule.
> chore(python): update python docs comments

- python/bullmq/worker.py
This PR adds the `WorkerOptions` typed dict class in the initializer for the python `Worker` class instead of a plain `dict`.
> chore(python): update worker class

- python/bullmq/queue.py
This PR adds the typed dict class `QueueOptions` for the python class `Queue`.
> chore(python queue): add QueueOptions

- python/tests/worker_tests.py
Removing unnecessary semicolons
> Removing unnecessary semicolons

- docs/gitbook/guide/flows/README.md
- tests/test_events.ts
ref https://github.com/taskforcesh/bullmq/issues/1711#issuecomment-1474768346
> docs(flows): add warning about queues configurations

- python/bullmq/error_code.py
- python/bullmq/job.py
- python/bullmq/queue.py
- python/bullmq/redis_connection.py
- python/bullmq/scripts.py
- python/bullmq/worker.py
- python/tests/queue_tests.py
there are several improvements as below:
- boolean identity to True and False
- type hinting
- trailing whitespace
- there should be two lines before class
- remove the semicolon in the test file
- remove unused imports
> refactor the code by removing white space, semicolon etc..

- src/classes/scripts.ts
- src/classes/worker.ts
- tests/test_events.ts
fixes https://github.com/taskforcesh/bullmq/issues/1312
> fix(worker): open handle

- python/bullmq/scripts.py
- src/classes/scripts.ts
- src/commands/reprocessJob-6.lua
- src/types/job-options.ts
- tests/test_worker.ts
fixes https://github.com/taskforcesh/bullmq/issues/1878
> fix(retry): consider when queue is paused

- docs/gitbook/guide/events.md
- tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/discussions/1912
> docs(events): add listener api references

- src/classes/scripts.ts
- src/commands/addJob-8.lua
- src/commands/moveJobFromActiveToWait-9.lua
- tests/test_rate_limiter.ts
fixes https://github.com/taskforcesh/bullmq/issues/1915
> fix(rate-limit): take in count priority

- src/commands/includes/moveJobFromWaitToActive.lua
- src/commands/includes/pushBackJobWithPriority.lua
- src/commands/moveJobFromActiveToWait-9.lua
- tests/test_rate_limiter.ts
fixes https://github.com/taskforcesh/bullmq/issues/1929
> fix(rate-limit): keep priority fifo order

- docs/gitbook/README.md
Fixes a broken link in the docs to patterns
> fix(docs): Update broken patterns link in the readme

- .github/workflows/api.yml
ref https://github.com/taskforcesh/bullmq/pull/2041
> ci(api): add docs-api branch logic

- python/README.md
- python/pyproject.toml
fixes https://github.com/taskforcesh/bullmq/issues/1979
> fix(python): add requires-python config

- docs/gitbook/SUMMARY.md
- docs/gitbook/guide/retrying-failing-jobs.md
- docs/gitbook/patterns/stop-retrying-jobs.md
- tests/test_rate_limiter.ts
ref https://github.com/taskforcesh/bullmq/issues/1571
> docs(retry): add stop retrying jobs pattern

- README.md
- fix broken logo
- correct "alt" value
> docs(readme): fix novu logo in used by section

- src/classes/queue-base.ts
- tests/test_queue.ts
https://github.com/taskforcesh/bullmq/issues/2120
> fix(queue): throw error when name is not provided

- package.json
- src/classes/worker.ts
- src/utils.ts
- tests/test_rate_limiter.ts
- tsconfig.json
- yarn.lock
fixes https://github.com/taskforcesh/bullmq-pro-support/issues/56
> fix(worker): abort rate-limit delay when closing worker

- docs/gitbook/changelog.md
- docs/gitbook/python/changelog.md
- package.json
- yarn.lock
ref https://github.com/TypeStrong/typedoc/pull/2370
> docs(typedoc): change default styling

- src/classes/queue-base.ts
- src/classes/redis-connection.ts
- src/interfaces/queue-options.ts
ref https://github.com/taskforcesh/bullmq/issues/2148
> feat(connection): provide skipVersionCheck option for shared connections

- tests/test_flow.ts
ref https://github.com/taskforcesh/bullmq/issues/2165
> test(flow): use removeOnComplete and age

- src/commands/moveToDelayed-8.lua
- tests/test_events.ts
ref https://github.com/taskforcesh/bullmq-pro-support/issues/60
> fix(delayed): trim events when moving jobs to delayed

- src/commands/addJob-9.lua
- src/commands/removeJob-1.lua
- tests/test_events.ts
ref https://github.com/taskforcesh/bullmq/pull/2225
> perf(events): trim events when removing jobs

- docs/gitbook/guide/jobs/job-ids.md
> docs(job-ids): clarify separators

- src/classes/queue.ts
- src/classes/repeat.ts
- src/interfaces/index.ts
- src/interfaces/repeatable-job.ts
- src/types/repeat-strategy.ts
- tests/test_repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/2300
> fix(repeat-strategy): add missing Promise return type

- docs/gitbook/SUMMARY.md
- docs/gitbook/bull/patterns/redis-cluster.md
- docs/gitbook/guide/redis-tm-hosting/README.md
- docs/gitbook/guide/redis-tm-hosting/aws-elasticache.md
- docs/gitbook/guide/redis-tm-hosting/aws-memorydb.md
- docs/gitbook/patterns/redis-cluster.md
- src/classes/job.ts
- tests/test_queue.ts
This reverts commit 6e677d2800957b368bef4247b8e4328c5758f262.
> fix(job): revert console warn custom job ids when they represent integers

- src/classes/child-processor.ts
- tests/fixtures/fixture_processor_esbuild.js
- tests/test_sandboxed_process.ts
> fix(sandboxed): better compatibility with esbuild

- src/classes/worker.ts
- tests/test_sandboxed_process.ts
> feat(sandbox): support URL (local files) as processor file

- src/classes/queue.ts
"othe high-level" should say "other..."
> Fix typo in src/classes/queue.ts

- docs/gitbook/guide/workers/sandboxed-processors.md
ref https://github.com/taskforcesh/bullmq/issues/2326 https://github.com/taskforcesh/bullmq/issues/2372
> docs(sandbox): add URL support section

- python/pyproject.toml
fixes https://github.com/taskforcesh/bullmq/issues/2361
> fix(redis): upgrade to v5 [python]

- tests/test_worker.ts
ref https://github.com/taskforcesh/bullmq/issues/2387
> test(prioritized): add test case when adding prioritized job with custom id

- src/classes/redis-connection.ts
- tests/test_connection.ts
Fixes https://github.com/taskforcesh/bullmq/issues/2385
> fix(redis-connection): close redis connection even when initializing

- src/classes/child-processor.ts
- src/classes/job.ts
- src/interfaces/sandboxed-job.ts
> fix(sandbox): extend SandboxedJob from JobJsonSandbox

- docs/gitbook/bullmq-pro/changelog.md
- docs/gitbook/patterns/process-step-jobs.md
> docs(bullmq-pro): update changelog with v7

- python/bullmq/job.py
- python/run_tests.sh
- python/tests/job_tests.py
ref https://github.com/taskforcesh/bullmq/issues/2472
> feat(job): add log method

- python/bullmq/worker.py
- src/classes/worker.ts
ref https://github.com/taskforcesh/bullmq/pull/2478#issuecomment-2006389005
> docs(block-timeout): document decision

- src/index.ts
- tsconfig.json
fixes https://github.com/taskforcesh/bullmq/issues/2502
> fix(deps): remove script loader from dist as it is used only when building package

- python/bullmq/queue.py
- python/bullmq/worker.py
- python/tests/job_tests.py
ref https://github.com/taskforcesh/bullmq/issues/2472
> feat(queue): add getJobLogs method [python]

- src/commands/moveStalledJobsToWait-9.lua
- tests/test_stalled_jobs.ts
fixes https://github.com/taskforcesh/bullmq/issues/2464
> fix(stalled): consider failParentOnFailure when moving child into failed

- src/classes/worker.ts
ref https://github.com/taskforcesh/bullmq/issues/2466
> perf(worker): reset delays after generating blockTimeout value

- src/classes/scripts.ts
> refactor(scripts): add protected moveStalledJobsToWaitArgs method

- src/classes/queue.ts
minor styling changes for consistency, a few caps here and there
> docs(queue): minor styling changes for consistency

- src/classes/job.ts
- src/classes/scripts.ts
- src/commands/addLog-2.lua
- src/commands/addLog-3.lua
- tests/test_job.ts
in order to prevent orphan keys
> fix(log): validate job existence

- docs/gitbook/guide/flows/README.md
ref https://github.com/taskforcesh/bullmq-pro-support/issues/71
> docs(flows): remove warning about beta usage

- python/bullmq/scripts.py
- python/bullmq/types/job_options.py
- python/bullmq/types/queue_options.py
- python/bullmq/utils.py
- python/bullmq/worker.py
- python/tests/bulk_tests.py
- python/tests/job_tests.py
- python/tests/queue_tests.py
- python/tests/worker_tests.py
- src/commands/includes/handleDuplicatedJob.lua
- tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/2554
> fix(parent): consider re-adding child that is in completed state with same jobIds

- src/classes/repeat.ts
- src/commands/addRepeatableJob-1.lua
- tests/test_delay.ts
- tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/2661
> fix(repeatable): keep legacy repeatables if it exists instead of creating one with new structure

- docs/gitbook/SUMMARY.md
- docs/gitbook/bullmq-pro/groups/prioritized.md
- docs/gitbook/changelog.md
- docs/gitbook/guide/parallelism-and-concurrency.md
- docs/gitbook/guide/queues/global-concurrency.md
- docs/gitbook/guide/workers/concurrency.md
- docs/gitbook/python/changelog.md
ref https://github.com/taskforcesh/bullmq/pull/2496
> docs(guide): add queue global concurrency section

- docs/gitbook/guide/jobs/repeatable.md
https://api.docs.bullmq.io/interfaces/v5.BaseJobOptions.html#repeatJobKey
> Update repeatable.md: fix repeat.key

- src/classes/scripts.ts
- src/commands/removeRepeatable-3.lua
- tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/2661
> fix(repeatable): remove repeat hash when removing repeatable job

- docs/gitbook/guide/retrying-failing-jobs.md
ref https://github.com/taskforcesh/bullmq/issues/2602
> docs(jobs): clarify example in retrying failing jobs guide

- docs/gitbook/python/introduction.md
> docs: update python docs example in introduction.md

- src/commands/moveStalledJobsToWait-9.lua
Missing to validate parentData variable before decoding in stalled check
> fix(flow): validate parentData before ignoreDependencyOnFailure when stalled check happens (python)

- src/classes/job.ts
- tests/test_job.ts
these option cannot be used together as they are exclusive
> fix(job): throw error if removeDependencyOnFailure and ignoreDependencyOnFailure are used together

- tests/test_events.ts
ref https://github.com/taskforcesh/bullmq/issues/2716
> test: remove debounceKey after job is removed in extended mode

- docs/gitbook/guide/jobs/debouncing.md
ref https://github.com/taskforcesh/bullmq/issues/2716
> docs(debouncing): add remove debounce key sub-section

- src/classes/queue.ts
- src/classes/repeat.ts
- src/classes/scripts.ts
- src/classes/worker.ts
- src/commands/addRepeatableJob-2.lua
- src/commands/updateRepeatableJobMillis-1.lua
- tests/test_repeat.ts
> fix(repeat): replace delayed job when updating repeat key

- tests/test_job.ts
ref https://github.com/taskforcesh/bullmq/issues/2744
> test(repeatable): add case when promoting a repeatable job

- src/classes/child.ts
- src/interfaces/worker-options.ts
- tests/test_sandboxed_process.ts
ref https://github.com/taskforcesh/bullmq/issues/1555
> feat(worker-thread): allow passing Worker Options

- src/classes/job-scheduler.ts
- tests/test_job_scheduler.ts
Fixes https://github.com/taskforcesh/bullmq/issues/1478
> fix(repeat): also consider startDate when using "every"

- src/classes/queue.ts
- src/interfaces/queue-options.ts
- src/utils.ts
- tests/test_queue.ts
Backport of getVersion to the v4.x branch
> feat(queue): add version support

- src/classes/job.ts
- src/classes/redis-connection.ts
- src/classes/scripts.ts
- tests/test_flow.ts
> fix: use-versions-for-lua-commands

- .github/workflows/release.yml
fixes https://github.com/taskforcesh/bullmq/issues/2868
> fix(commands): add missing build statement when releasing [python]

- docs/gitbook/patterns/process-step-jobs.md
ref https://github.com/taskforcesh/bullmq/issues/490
> docs(patterns): fix token type in process-step-jobs

- .github/workflows/test.yml
- package.json
- tests/test_sandboxed_process.ts
- yarn.lock
ref https://github.com/taskforcesh/bullmq/issues/2747
> fix(deps): bump msgpackr to 1.1.2 to resolve ERR_BUFFER_OUT_OF_BOUNDS error

- src/classes/job-scheduler.ts
Fixes https://github.com/taskforcesh/bullmq/issues/2860
> fix(repeatable): only apply immediately in the first iteration

- tests/test_flow.ts
ref https://github.com/taskforcesh/bullmq/issues/2909
> test(flow): add test case where child has a delay

- src/classes/job-scheduler.ts
- src/enums/telemetry-attributes.ts
- tests/test_job_scheduler.ts
- tests/test_telemetry_interface.ts
#fixes https://github.com/taskforcesh/bullmq/issues/2912
> feat(job-scheduler): add telemetry support to the job scheduler

- src/classes/queue-base.ts
- src/classes/worker.ts
- src/interfaces/repeat-options.ts
- tests/test_telemetry_interface.ts
- tests/test_worker.ts
as reference of https://github.com/taskforcesh/bullmq/issues/2860#issuecomment-2466523399
> fix(scheduler): remove deprecation warning on immediately option

- src/classes/job-scheduler.ts
- src/classes/queue.ts
- tests/test_job_scheduler.ts
Added a missing method for the job schedulers api
> feat(job-scheduler): add getJobSchedulersCount method

- src/classes/index.ts
> chore: export child type

- .github/workflows/test.yml
- src/classes/job-scheduler.ts
- src/classes/scripts.ts
- src/commands/includes/addDelayedJob.lua
- src/commands/updateJobScheduler-6.lua
- tests/test_job_scheduler.ts
1. Why is this change necessary? In order to support server less Redis for schedulers
1. How did you implement this? Create new script to handle, update and addition of a new delayed job
> perf(job-scheduler): add delayed job and update scheduler in same script

- tests/test_sandboxed_process.ts
1. Why is this change necessary? In order to use the same file in pro version
> test(sandboxed): change Child import reference

- tests/fixtures/fixture_processor_ttl.js
- tests/test_sandboxed_process.ts
Adds a test to verify that the Sandboxed TTL pattern works.
By implementing the pattern in a test.
https://docs.bullmq.io/patterns/timeout-for-sandboxed-processors
> test: add test for sandbox ttl pattern

- src/classes/job-scheduler.ts
- src/commands/addJobScheduler-6.lua
- src/commands/updateJobScheduler-7.lua
- src/interfaces/job-scheduler-json.ts
- tests/test_job_scheduler.ts
1. Why is this change necessary? In order to show how many iterations are being made
1. How did you implement this? Add new ic attribute to save this value
> feat(job-scheduler): save iteration count

- docs/gitbook/bull/patterns/persistent-connections.md
- docs/gitbook/guide/connections.md
- docs/gitbook/guide/metrics/README.md
- docs/gitbook/guide/metrics/prometheus.md
1. Why is this change necessary? To clarify the usage of maxRetriesPerRequest option from ioredis
1. How did you implement this? Add clarification in connections section
> docs(connections): clarify maxRetriesPerRequest usage

- src/classes/job-scheduler.ts
- src/commands/addJobScheduler-6.lua
- src/interfaces/job-scheduler-json.ts
- src/interfaces/repeatable-options.ts
- tests/test_job.ts
- tests/test_job_scheduler.ts
1. Why is this change necessary? limit option is missing when saving job scheduler metadata
1. How did you implement this? Pass this option when storing job scheduler
> feat(job-scheduler): save limit option

- README.md
A link to a logo was using insecure http instead of https.
Just changed to use https.
> docs: fix link to use https

- src/classes/worker.ts
fixes https://github.com/taskforcesh/bullmq/issues/3055
> fix: fix return type of getNextJob

- tests/test_job_scheduler.ts
1. Why is this change necessary? To demonstrate that delayed jobs that are generated by job schedulers, support priorities
1. How did you implement this? Check that prioritized count is 1, once delayed job is promoted
> test(job-scheduler): check that delayed job from scheduler supports priorities

- src/commands/addJobScheduler-2.lua
- src/commands/includes/storeJobScheduler.lua
1. Why is this change necessary? separate storeJobScheduler include reduce code in addJobScheduler
1. How did you implement this? Extract storeJobScheduler in an include file
> refactor(scheduler): separate storeJobScheduler include

- src/classes/job-scheduler.ts
- src/commands/includes/storeJobScheduler.lua
- tests/test_job_scheduler.ts
1. Why is this change necessary? Save limit option that is provided when creating a job-scheduler
1. How did you implement this? Pass limit option to storeJobScheduler include
for reference https://github.com/taskforcesh/bullmq/pull/3033
> fix(job-scheduler): restore limit option

- src/classes/queue.ts
- tests/test_concurrency.ts
1. Why is this change necessary? In order to revert a global concurrency setting
1. How did you implement this? Remove global concurrency option from meta
> feat(queue): support removeGlobalConcurrency method

- tests/test_worker.ts
1. Why is this change necessary? Fix flaky test when pausing worker
> test(worker): fix flaky test when pausing worker

- src/classes/job-scheduler.ts
- src/classes/scripts.ts
- src/commands/addDelayedJob-6.lua
- src/commands/addJobScheduler-10.lua
- src/commands/addJobScheduler-9.lua
- src/commands/includes/addDelayedJob.lua
1. Why is this change necessary? As part of giving support to serverless dbs
1. How did you implement this? Move addition of delayed job when adding job scheduler
> refactor(scheduler): remove multi when adding a job scheduler

- src/classes/job.ts
1. Why is this change necessary? As reference https://github.com/taskforcesh/bullmq/pull/3111
1. How did you implement this? Send different span names depending on which operation happens when failing a job
> fix(telemetry): fix span name for moveToFailed logic

- src/commands/addJobScheduler-10.lua
- tests/test_flow.ts
1. Why is this change necessary? Test failed randomly in dragonfly.
1. How did you implement this? Run workers after preparation
> test(flow): fix flaky test when parent has delay

- docs/gitbook/bullmq-pro/nestjs/changelog.md
- docs/gitbook/python/changelog.md
1. Why is this change necessary? In order to reflect new version in nests-bullmq-pro
ref https://github.com/taskforcesh/issues/issues/180
> docs(nestjs-bullmq-pro): update changelog to v3.1.0

- src/classes/job.ts
1. Why is this change necessary? Missing span when completing a job, only failures have spans right now
1. How did you implement this? Add complete span in moveToCompleted method
> feat(job): add complete span in moveToCompleted method

- tests/test_job_scheduler.ts
> test(scheduler): fix flaky test

- docs/gitbook/guide/redis-tm-hosting/aws-elasticache.md
> docs(aws-elasticache): fix typo

- tests/test_delay.ts
- tests/test_events.ts
- tests/test_sandboxed_process.ts
> test(events): fix flaky test

- .github/workflows/osv-scanner.yml
We use dependabot, but OSV scanner seems to be more comprehensive.
Adding a new GitHub Action.
> ci: add osv-scanner workflow

- src/classes/queue-events.ts
- tsconfig.json
1. Why is this change necessary? Because cannot it cannot resolve JobProgress type
1. How did you implement this? Replace path to correct directory
fixes https://github.com/taskforcesh/bullmq/issues/3191
> fix(queue-events): pass right path for JobProgress type

- src/classes/queue-getters.ts
- src/classes/redis-connection.ts
normalize line splitting for cross-platform compatibility
#3204
> fix: fix version lines split

- src/commands/includes/removeJobWithChildren.lua
> chore: fix lint error in script file

- src/classes/job.ts
- src/commands/moveStalledJobsToWait-9.lua
- src/interfaces/job-json.ts
- tests/test_stalled_jobs.ts
1. Why is this change necessary? In order to know how many times a job has stalled
1. How did you implement this? Expose stalledCounter attribute 
> feat(job): expose stalledCounter attribute

- src/classes/job.ts
- src/utils.ts
1. Why is this change necessary? In order to allow extension when new options are added in pro versions
> refactor: expose opts decode and encode maps for extension

- src/classes/queue-events-producer.ts
- src/interfaces/queue-options.ts
to fix this issue: https://github.com/taskforcesh/bullmq-otel/issues/8
Just omit the unused telemetry option.
> fix(queue-events): omit telemetry options

- src/classes/flow-producer.ts
- src/classes/job.ts
- src/classes/scripts.ts
- src/commands/includes/moveJobFromPrioritizedToActive.lua
- src/commands/moveToActive-11.lua
- src/commands/moveToFinished-14.lua
- src/interfaces/base-job-options.ts
- src/interfaces/index.ts
- src/interfaces/minimal-job.ts
- src/interfaces/parent-options.ts
- src/interfaces/parent.ts
- src/utils.ts
1. Why is this change necessary? Refactor few types to be reused and add new protected methods for extension in pro package
> refactor(scripts): add protected methods to get args for extension

- docs/gitbook/bullmq-pro/install.md
There has been slight typo in installation step for BullMQ Pro
Changed `NPM__TASKFORCESH__TOKEN` to `NPM_TASKFORCESH_TOKEN`
> docs: update environment variable typo in install.md

- src/classes/worker.ts
1. Why is this change necessary? No need to create new callbacks in every job processing
> refactor(worker): convert handler callbacks to worker methods

- docs/gitbook/changelog.md
- package.json
1. Why is this change necessary? Last attempt to create a pr for updating changelog and version failed, but new version was published
> docs(changelog): update to v5.53.3

- docs/gitbook/guide/retrying-failing-jobs.md
- src/classes/backoffs.ts
- src/classes/job.ts
- src/interfaces/backoff-options.ts
- tests/test_job.ts
- tests/test_worker.ts
1. Why is this change necessary? In some scenarios we should be able to apply jitter strategy when applying a backoff
> feat(backoff): add jitter option

- docs/gitbook/changelog.md
- package.json
1. Why is this change necessary? Last attempt to create a pr for updating changelog and version failed, but new version was published
> docs(changelog): update to v5.54.0

- .github/workflows/release.yml
Remove skip ci from commit message so that PRs created by the release action are actually run.
> ci: fix release so that it runs checks

- src/commands/moveJobFromActiveToWait-9.lua
- tests/test_rate_limiter.ts
1. Why is this change necessary? When job does not exists must throw a different error message
> fix(rate-limit): throw right error message if job does not exist

- src/commands/moveToWaitingChildren-8.lua
- tests/test_flow.ts
1. Why is this change necessary? Removal of job from active state was missed
1. How did you implement this? Add logic to handle job removal from that state when it's planned to be moved to failed
> fix(flow): remove parent from active when there are unsuccessful children

- package.json
- yarn.lock
> ci(deps): upgrade form-data sub-dependency to v4.0.4

- package.json
- yarn.lock
1. Why is this change necessary? Resolution is not needed anymore as part of last upgrade of coveralls-next
1. How did you implement this? Upgrade coveralls-next to v5
> ci: upgrade coveralls-next to v5 to remove resolution

- package.json
- yarn.lock
> ci(deps): upgrade tmp to v0.2.4

- docs/gitbook/changelogs/changelog-v4.md
1. Why is this change necessary? v4.18.3 was released few days ago. Changelog need to be updated to reflect this new version 
> docs(changelog): update changelog v4 to v4.18.3

- README.md
- docs/gitbook/patterns/throttle-jobs.md
> docs(readme): add ref of flowProducer and throtling

- .husky/pre-commit
- package.json
- src/index.ts
1. Why is this change necessary? As part of previous refactor, Processor type was missed to be exported
ref https://github.com/taskforcesh/bullmq/pull/3416
> fix(types): export processor type

- docs/gitbook/guide/parallelism-and-concurrency.md
> docs(guide): Fix typo in parallelism-and-concurrency

- docs/gitbook/changelog.md
- docs/gitbook/python/changelog.md
> docs(changelog): update python changelogs to nodejs format

- docs/gitbook/changelog.md
- docs/gitbook/python/changelog.md
> docs(changelog): update python changelog to use semantic format

- package.json
- yarn.lock
1. Why is this change necessary? uuid is not using its native uuid generation by default but it's being fixed in v11 https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#1100-2024-10-26
> fix(deps): upgrade uuid to v11

- src/classes/job.ts
- tests/test_queue.ts
- tests/test_telemetry_interface.ts
1. Why is this change necessary? Similar to https://github.com/taskforcesh/bullmq/pull/2719 but at jobId level. There was a message being added some time ago in https://github.com/taskforcesh/bullmq/pull/2251, but an actual error is missing
1. How did you implement this? Throw error when : is contained in custom job id
fixes https://github.com/taskforcesh/bullmq/issues/3382
> fix(job): add custom job id validation to prevent : inclusion

- package.json
- tests/test_flow.ts
- tests/test_job.ts
- tests/test_repeat.ts
1. Why is this change necessary? Test files were ignored from prettier
> chore(deps): consider test files when applying prettier
