taskforcesh/bullmq

src/classes/master.ts, src/test/fixtures/fixture_processor_progress.js, src/test/test_sandboxed_process.ts
Originally implemented by @douglascayers, ported from Bull3 (https://github.com/OptimalBits/bull/pull/1536).
=> job.progress() return last progress for sandboxed processors

src/classes/job.ts, src/classes/sandbox.ts, src/test/test_job.ts
renames Job#toJSON to Job#asJSON and adds a test
=> fix: avoid changing Job property types through JSON serialization/deserialization #70

src/commands/moveToFinished-7.lua, src/test/test_job.ts
=> fix: check in moveToFinished to use default val for opts.maxLenEvents

package.json, src/classes/queue-events.ts, src/classes/worker.ts, src/test/fixtures/delay.js, src/test/fixtures/fixture_processor.js, src/test/fixtures/fixture_processor_bar.js, src/test/fixtures/fixture_processor_exit.js, src/test/fixtures/fixture_processor_fail.js, src/test/fixtures/fixture_processor_foo.js, src/test/fixtures/fixture_processor_progress.js, src/test/fixtures/fixture_processor_slow.js, src/test/test_clean.ts, src/test/test_compat.ts, src/test/test_job.ts, src/test/test_pause.ts, src/test/test_sandboxed_process.ts, src/test/test_stalled_jobs.ts, src/test/test_worker.ts, src/utils.ts, yarn.lock
This approach uses a simple setTimeout-based delay in the only production
usage (src/classes/queue-events.ts), defined in src/util.ts, and since
there was already a devDependency on a library called
[delay](https://www.npmjs.com/package/delay), this commit uses that in
test contexts. It should be easy to replace that dep with a
`(ms:number) => new Promise(r => setTimeout(r, ms))` as well.
Closes #67
=> feat: remove dependence on Bluebird and delay #67

docs/gitbook/what-is-bullmq.md
Attempt to close #56 by adding a note on the _What is BullMQ_ docs page
=> docs: add github link to what-is-bullmq.md

src/classes/redis-connection.ts, src/classes/worker.ts, src/utils.ts
Should fix #90.
I changed 2 things:
- In worker.ts, the blocking connection was not duplicated because the condition did not use `opts.connection` but `opts`
- In worker.ts and redis-connection.ts, the condition used to check that it was a Redis instance was using `instanceof` which is not totally reliable depending on the environnement (if multiple instance of the package `ioredis` exist through the app, it will not work)
=> fix: check of existing redis instance

src/classes/compat.ts, src/classes/queue-events.ts, src/test/test_bulk.ts, src/test/test_clean.ts, src/test/test_compat.ts, src/test/test_connection.ts, src/test/test_delay.ts, src/test/test_events.ts, src/test/test_getters.ts, src/test/test_job.ts, src/test/test_pause.ts, src/test/test_queue.ts, src/test/test_rate_limiter.ts, src/test/test_repeat.ts, src/test/test_sandboxed_process.ts, src/test/test_stalled_jobs.ts, src/test/test_worker.ts, src/utils.ts
Replace flushdb with direct queue keys removal.
Fix unstable test (looks like it started to fail on my env after 3c5b01d1).
Fixes #102
=> fix: get rid of flushdb/flushall in tests

src/classes/queue-base.ts
Noticed that `active` was in the keys list twice for events. I understand that functionally this does not affect anything but figured it was still good to clean up.
=> [fix] Remove duplicate active entry

src/classes/queue.ts
The `addBulk` signature was missing the data type and the `name` parameter did not match between the two methods.
=> fix: cleanup signatures for queue add and addBulk

src/classes/master.ts, src/interfaces/index.ts, src/interfaces/sandboxed-job-processor.ts, src/interfaces/sandboxed-job.ts
At first: I don't know what's the PR format, I just wanted to make working with this library a little less frustrating by adding processor types.
So with this change you can write your processors like:
```typescript
const processor: SandboxedJobProcessor<string> = async (job) => {
job.progress(0);
// do some stuff with `job.data` or smth...
job.progress(100);
return 'done';
};
export default processor;
```
=> feat(types): add sandboxed job processor types

src/classes/child-pool.ts
Hi,
My child processes are crashing if I start Node with the inspect flag. I see that there is already some code in place to handle this, but it doesn't seem to be working.
`Starting inspector on 0.0.0.0:5858 failed: address already in use`
> {"job":{"id":"9","name":"test2","data":"{\"objectType\":\"users\",\"objectId\":\"52786\",\"delete\":false}","opts":"{\"attempts\":0,\"delay\":0,\"removeOnComplete\":true,\"removeOnFail\":true}","progress":0,"attemptsMade":1,"processedOn":1581530442512,"timestamp":1581530442516,"failedReason":"\"Unexpected exit code: 12 signal: null\"","stacktrace":"[\"Error: Unexpected exit code: 12 signal: null\\n    at ChildProcess.exitHandler (/application/node_modules/bullmq/dist/classes/sandbox.js:34:24)\\n  at ChildProcess.emit (events.js:228:7)\\n    at …
=> fix: fixed exit code 12 when using inspect with child process

src/classes/child-pool.ts, src/classes/job.ts, src/classes/redis-connection.ts, src/classes/timer-manager.ts, src/classes/worker.ts, src/commands/index.ts, src/interfaces/queue-options.ts, src/interfaces/redis-options.ts, src/test/test_bulk.ts, src/test/test_clean.ts, src/test/test_compat.ts, src/test/test_connection.ts, src/test/test_delay.ts, src/test/test_events.ts, src/test/test_getters.ts, src/test/test_job.ts, src/test/test_pause.ts, src/test/test_queue.ts, src/test/test_rate_limiter.ts, src/test/test_repeat.ts, src/test/test_sandboxed_process.ts, src/test/test_stalled_jobs.ts, src/test/test_worker.ts, src/utils.ts, tsconfig.json
This change should enable compatibility with top-level projects that have esModuleInterop disabled.
I did not include any tests since I disabled esModuleInterop in BullMQ. This should cover any future issues.
Fixes GH-129.
=> fix: modified imports to work when esModuleInterop is disabled

src/classes/job.ts
Uncommented out line of code that sets/restores the job timestamp from the job's JSON data.
#138
=> fix: restore the Job timestamp when deserializing JSON data (#138)

src/classes/sandbox.ts
This fix comes from bull.
Reference: 
https://github.com/OptimalBits/bull/issues/1460
https://github.com/OptimalBits/bull/pull/1461
=> fix(sandbox): If the child process is killed, remove it from the pool.

docs/gitbook/guide/connections.md
I am not sure exactly the options here, but definitely this will work.  It also appears that some sort of resolution might occur if a string is passed, but I can't figure that one out.
=> Second Argument for worker is missing

src/classes/queue-scheduler.ts
Assume we have one deleayed job. 
Scheduler on start loads incorrect local nextTimestamp value 6513388584960082.
It isn't divided by 4096 in https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-scheduler.ts#L51-L58
So for every iteration the following code wouldn't be executed. It does not set the next timestamp for execution in delay stream: https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-scheduler.ts#L101-L112
I don't know how to write test suite for such case. But this fix helps to alive our frozen cron tasks in production.
BTW for what purpose do you divide & multiply timestamp by 4096? We really spent a lot of time to figure out this mistake.
=> fix: Scheduler does not set the next record to delay stream

docs/gitbook/guide/jobs/stalled.md, docs/gitbook/guide/queuescheduler.md
- add hint on the `stalled jobs` page
- updates QueueScheduler description
=> docs: improve QueueScheduler docs

docs/gitbook/guide/connections.md, src/classes/redis-connection.ts, src/commands/index.ts
resolves #108, resolves #79, resolves #59 
I think all the different initialization cases are fixed by this change. When re-using a redis client, the ready event is not triggered so the `load` function was not being called in this case.
=> fix(redis-connection): run the load command for reused redis client

src/classes/queue.ts
The current comment refers to a `remove` function that no longer exists.
Now, clean is similar to drain?
=> docs: fix clean comment

src/classes/child-pool.ts, src/classes/master.ts, src/classes/process-utils.ts, src/classes/worker.ts, src/test/test_child-pool.ts, src/test/test_sandboxed_process.ts
Properly handle SIGTERM in the child workers by waiting for the current
job to exit, then exiting cleanly.
Worker#close now also kills the workers and waits for them to close
This is the same feature as https://github.com/OptimalBits/bull/pull/1802
=> feat(sandbox): kill child workers gracefully

package.json
If a user wishes to pull in a version of bullmq via the git/github syntax as supported by npm, the resulting code will not work before this change.  This is because npm will not invoke the `prepublish` target to compile the TS code.  However it will invoke the `prepare` target which is a superset of the `prepublish` target.  Thus it makes sense to rename the `prepublish` taret to `prepare` as that is a more desirable behavior.  More can be read on it at https://docs.npmjs.com/files/package.json. 
This change also sorts the targets because sorting is good.
=> build: sort script targets, rename prepublish target to prepare

src/classes/compat.ts, src/classes/job.ts, src/classes/queue.ts, src/classes/sandbox.ts, src/classes/scripts.ts, src/classes/worker.ts, src/interfaces/worker-options.ts
Was looking into how I could setup BullMQ with typed job names (to ensure no unhandled jobs are added to queues). Ended up adding a few new generics to support those new types. Big ones are adding two new generics to Queue and Worker: job return values and job names, as well as augmenting the Processor with the same Queue and Worker generics.
Didnt change any actual code other than a small fix in `src/classes/sandbox.ts`. With new types, tslint didn’t like the unhandled promises in the msgHandler.
Been using BullMQ for some time now but not super familiar with the codebase itself, let me know if there’s anything you’d like me to change with this! 
Side note: I'm a huge fan of Bull, amazing piece of technology!
=> Fix job types

src/classes/worker.ts
In Google Cloud memorystorage redis v5 the error that throw when you use client is:
```bash
root@tortilla2-8649d75859-nbmmh:/usr/src/app# netcat redis-memorystore 6379
client id
-ERR unknown command `client`, with args beginning with: `id`,
```
I update regex to get this error too
=> Fix clientCommandMessageReg

src/classes/scripts.ts, src/commands/promote-5.lua, src/test/test_job.ts
Hi,
I believe I found a bug that leads to jobs disappearing from the waiting queue if they where added while the queue was paused. This is the shortest example I could create that reproduces the error, no workers are needed:
```
const Queue = require('bullmq').Queue;
const queue = new Queue('bugtest');
(async () => {
await queue.drain();
const first = await queue.add('first', null);
const second = await queue.add('second', null, {delay: 1});
await queue.pause();
await second.promote();
await queue.resume();
console.log(await queue.getWaitingCount()); // Should output 2, actually 1
console.log(await second.getState()); // Should output waiting, actually 'unknown'
queue.close();
})()
```
After some investigation I think the root cause is how the promote Lua script is implemented:
```
--[[ …
```
=> Fix disappearing jobs when promoted on paused queue

src/classes/queue.ts, src/test/test_pause.ts
Currently it is possible to pause a queue or resume it but there were no way to find out if a queue is paused or not.
Directly using Redis commands would be an anti-pattern in my opinion as the name of the keys and the way how paused state is stored should be an internal detail that the users should not be aware of or interfere with.
I created a public method in the Queue class that exposes if it is paused or not. If the implementation should be renamed or replaced, I'm happy to move it around.
=> feat: add ability to get if queue is paused or not

src/classes/queue.ts, src/classes/worker.ts
Fixes a bug where the `Repeat` created in the worker for repeat jobs does not have an error handler installed, which causes an uncaught exception even if an error handler is installed on the worker in the event of a Redis network error, for example.
=> fix(worker): catch errors from created Repeat

docs/gitbook/guide/jobs/repeatable.md
The previously linked generator uses the non-standard Quartz "cron" format. The new link is a standard unix cron entry generator.
Addresses part of #305 .
=> Replace link to crontab generator, which used the wrong format.

src/interfaces/advanced-options.ts, src/interfaces/backoff-options.ts, src/interfaces/jobs-options.ts, src/interfaces/queue-options.ts, src/interfaces/queue-scheduler-options.ts, src/interfaces/rate-limiter-options.ts, src/interfaces/repeat-options.ts, src/interfaces/sandboxed-job-processor.ts, src/interfaces/sandboxed-job.ts, src/interfaces/worker-options.ts
- Block comments for IDE support / "intellisense"
- Add links to the docs for further reading
- For links, I used the format described at https://tsdoc.org/pages/tags/see/
=> docs(interfaces): use block comments; add references and descriptions

src/classes/job.ts
Before this change, `job.waitUntilFinished` did a smart check at the start to see if the job had already been completed. This makes sense -- the QueueEvents object is never going to send another `completed` event for a job that has already been completed, so we need to make sure that we're not listening for an event that never comes.
The problem is that there's a finite amount of time between when we make this first check and when we start listening to the queue events. There is a window after we make the check and before we are listening for the completed event. For very quick to process jobs, they can emit their completed event in this window, so the listeners never find it. The `waitUntilFinished` will fail with a timeout, but the job did actually complete.
This switches the order in …
=> Fix a bug where waiting for a job to complete can timeout if the job finished faster than the listeners can be registered

src/classes/job.ts
Not a huge change but helps when debugging complicated systems that are talking to multiple different backends to identify which piece exactly timed out. 🤷
=> Improve job timeout notification by giving the job name and id in the error message

src/interfaces/queue-options.ts
This PR resolves https://github.com/taskforcesh/bullmq/issues/324.
[QueueBaseOptions](https://github.com/taskforcesh/bullmq/blob/5e6631e7c3f40b7857d2f73b48abfd3f9d072b35/src/interfaces/queue-options.ts#L11) has a `client` property that is not used by the code:
https://github.com/taskforcesh/bullmq/blob/5e6631e7c3f40b7857d2f73b48abfd3f9d072b35/src/interfaces/queue-options.ts#L13
Indeed, instead the `connection` property is used:
https://github.com/taskforcesh/bullmq/blob/5e6631e7c3f40b7857d2f73b48abfd3f9d072b35/src/classes/queue-base.ts#L23
Note that this is not related to the [client getter](https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L57) which also uses the aforementioned `connection` property: …
=> fix: remove "client" property of QueueBaseOptions (#324)

package.json, src/test/test_repeat.ts, yarn.lock
This upgrade is in order to support the new methods in redis client, since now we cannot use lpos directly for example. After this PR is approved I could update #445
=> Upgrade ioredis

src/classes/flow.ts, src/classes/job.ts, src/classes/queue.ts, src/classes/scripts.ts, src/commands/getState-7.lua, src/commands/getStateV2-7.lua, src/test/test_flow.ts
We should also consider waiting-children when getting an state for a job. Also I was playing with getDependencies and I got an error so I tried to take the opportunity to fix it here.
=> Consider waiting-children state when getState

src/classes/flow-producer.ts, src/classes/index.ts, src/test/test_flow.ts
This is actually a breaking change, but I took the freedom to release it as a fix since flows are a pretty new feature and I do not expect anybody to actually use it it production yet.
=> fix: rename Flow to FlowProducer class

src/commands/moveToFinished-7.lua, src/test/test_job.ts
This PR updates the current test that were failing, the reason was that workers were missing, so the jobs were getting waiting state #64
=> Throw an error if job is not in active state when moveToCompleted

package.json, src/test/test_connection.ts, src/test/test_job.ts, src/test/test_sandboxed_process.ts, src/test/test_worker.ts, tsconfig.json
Currently, a lot of files are published, docs, dist, src, ... etc. We can just publish the ones that are in dist since these files are built. you can now use yarn dry-run to see which files are going to be published to verified this, also with this change we are going to decrease the size of this package a lot.
=> Just publish dist files

src/classes/flow-producer.ts, src/classes/scripts.ts, src/commands/moveToFinished-7.lua, src/test/test_job.ts, src/test/test_repeat.ts
Currently we can manually move parent to complete, even if it has children. We should verify that this job does not have pending children first, if not throw an error
=> Fix moveToComplete, should not move to complete before children

src/classes/queue.ts, src/classes/repeat.ts
By adding correct typings for the `addNextRepeatableJob` function, `Queue`'s  `add` will have a proper return type (`Promise<Job<T, R, N>>` instead of `Promise<Job<any, any, string>>`).
Based on #472
=> feat: add typing for addNextRepeatableJob

src/interfaces/index.ts
this allows to do `import { FlowJob } from "bullmq";` instead of `import { FlowJob } from "bullmq/dist/interfaces/flow-job";`
=> fix export of FlowJob interface

src/classes/job.ts
Hi
Method `job.waitUntilFinished()` returns the job's returnvalue when resolving but its return type is not specified (resulting in `Promise<any>`)
This PR fixes this typing issue.
=> fix: add return type for job.waitUntilFinished()

src/classes/job.ts, src/classes/redis-connection.ts, src/classes/worker.ts
This PR tries to fix the release failure generated by this pr #514, what I did is change how RedisClient was constructed, previously it was transpiled with an import declaration, now it is build without it, also I run yarn docs locally and the error is gone
=> Fix RedisClient type

docs/gitbook/guide/jobs/flows.md
Fixed a typo in the code snippet inside `flows.md` file.
Also, the same typo exists in the `parent-child-jobs.md`, but I didn't include it into this PR, as this file seems to be unused. Maybe we could simply remove that file.
=> docs: fix typo in flows.md

src/classes/flow-producer.ts, src/classes/job.ts, src/test/test_flow.ts
=> Fix flowProducer: use custom jobId as parentId for children

src/classes/worker.ts, src/test/test_pause.ts
Fixes https://github.com/taskforcesh/bullmq/issues/160
Currently, if we pause a worker while waiting to pop off the next job, we disconnect. The issue is that `this.waiting` can change to `false` before we try to reconnect, preventing us from reconnecting, even if it was requested (which is it, when pausing). Once we resume, the connection is closed, causing the `run` loop to throw `Client is disconnected` (since we're neither paused nor closing).
We fix this by _only_ checking the `reconnect` argument. To handle the case where we didn't disconnect, we just set reconnect to `false` so that we don't try to reconnect.
**For reviewers**
I believe it's clear that this can happen, and I've observed it in a flaky test suite in my company's CI, but I'm struggling to write a test for it. Maybe …
=> Ensure connection reconnects when pausing.

src/classes/job.ts, src/test/test_bulk.ts, src/test/test_job.ts, src/test/test_worker.ts
When we want to wait for all the children we could pass no opts to moveToWaitingChildren
=> Fix moveToWaitingChildren: opts should be optional

src/classes/flow-producer.ts, src/classes/job.ts, src/test/test_flow.ts
This method tries to help in getting and entire flow from a parent reference. Also as we can have a lot of children for a job I think is a good idea to limit this method by a max children and depth level, so we don't too much information
=> Feat getFlow method

src/test/test_worker.ts
There is one comment to be aware when using sscan and hscan, here is explained in the documentation https://redis.io/commands/scan#why-scan-may-return-all-the-items-of-an-aggregate-data-type-in-a-single-call
=> Fix flaky test related to getDependencies

src/classes/job.ts, src/test/test_flow.ts
when using Object.assign we are assigning values to the first param, so the defaultOpts are changed the first time that Object.assign is called, so in order to keep the defaultOpts immutable, we should spread its values in a new object when using that method.
=> Fix getDependencies defaultOpts

src/classes/job.ts, src/classes/scripts.ts, src/test/test_flow.ts
As we have getFlow method, we can get a tree for an specific parent node, but in order to know from which queue the children and grand children belong, it would be nice to expose the name of the queue from the job instance.
=> Feat expose queueName in job

src/classes/redis-connection.ts
Fixed an issue where event listeners on shared redis connections meant that Workers which had been "closed" were holding onto references to redis-connection in memory.
I believe this will also fix the issue described in #167
=> fix(redis-connection): remove event listeners from shared client

package.json, src/classes/queue-events.ts, src/classes/worker.ts, src/test/test_events.ts, src/test/test_sandboxed_process.ts
The actual drained event does not contain other args apart of event name, the typing was expecting that the event id is passing so I updated the logic here, also the active typing was wrong so it's updated now. I noticed that there are not keywords, so I added some what do you think https://docs.npmjs.com/cli/v7/configuring-npm/package-json#keywords?
=> Fix missing event typing

src/classes/queue-scheduler.ts, src/classes/worker.ts
Hey everyone,
we sometimes run into the problem, that the worker stops doing its job. I've added this code for a possibility to check, if the "run()" loop is still up and healthy so that i can restart my process in case it is not.
Would be great to have this as soon as possible since we had some bigger issue in some of our projects the last day regarding died workers.
Thanks,
Sven
=> feat(worker+scheduler): add a "running" attribute for healthchecking

src/classes/queue.ts
In my app we disconnect queues sometimes quite quickly after constructing them, and see this error every so often in our CI logs:
```
/app/node_modules/bullmq/node_modules/ioredis/built/redis/index.js:620
command.reject(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
^
Error: Connection is closed.
at Redis.sendCommand (/app/node_modules/bullmq/node_modules/ioredis/built/redis/index.js:620:24)
at Redis.hset (/app/node_modules/bullmq/node_modules/ioredis/built/commander.js:111:25)
at /app/node_modules/bullmq/src/classes/queue.ts:29:14
```
I am not exactly sure why it only happens sometimes but not others, but regardless, I think it's a good idea not to try to run the floating `hset` in the queue constructor if the client has been closed. This prevents that by first checking if the client …
=> fix(queue): ensure the Queue constructor doesn't try to hset queue options if the client is closed

src/classes/redis-connection.ts
Summary: When supplying your own IORedis instance and `lazyConnect` is true, the RedisConnection instance will not connect on its own because it does not check if it's `status` is "wait". While this may be intended behavior, there is no direct way to call `connect` on the duplicated Redis instance causing it to never connect and indefinitely wait until ready.
Context: Came across this issue when trying to create unit tests for my application. I didn't look at any guidelines for PRs or issues because its such a simple fix so if you don't merge mine at least you know the problem and how to fix it yourself.
=> Hotfix for connection hanging when `close()`

src/classes/redis-connection.ts, src/test/test_connection.ts
Update the `RedisConnection.waitUntilReady` static method to better reflect the internal ioredis status.
=> fix: connection hangs with failed connection

src/classes/queue-getters.ts, src/classes/worker.ts, src/utils.ts
This is in order to avoid circular references, taking this PR #611 as base for this fix (here tests are running)
=> Fix: move clientCommandMessageReg to utils

src/classes/redis-connection.ts, src/test/test_connection.ts
Following #666 I tried to address this issue, so I don't see this log
```sh
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
```
anymore when running the test
=> Fix redis-connection: add error event in waitUntilReady

src/classes/queue.ts, src/test/test_rate_limiter.ts, src/test/test_worker.ts
when processing a job that does not have a groupKey, the id is generated with undefined at the end, so every job with this content also ends with undefined too
=> Fix rateLimiter: check groupKey is not undefined

contributing.md, docker-compose.yml, package.json, src/test/test_rate_limiter.ts, src/test/test_worker.ts
This PR allows windows users to run tests locally. Sometimes I'm using Windows to work in this package, so I use redis docker-compose in order to set redis locally, also https://github.com/microsoftarchive/redis/releases this is pretty old. In order to test this you could run the scripts yarn dc:up to start redis then you could use yarn test, test in Windows should run without problem.
Note: the docker-compose file is not included in releasable files, to check this, you can run yarn dry-run
=> Add redis docker-compose to support windows development

docs/gitbook/guide/jobs/proritized.md
linter was applied to those files when editting
=> docs(prioritized): fix typo

package.json, src/classes/worker.ts
processing.keys() returns a **Map Iterator**, in Promise.all expects an array of promises, so this is fixed by applying an spread operator, so it returns now `[ Promise { <pending> } ]`
=> fix(worker): use spread operator in processing map keys

src/classes/scripts.ts, src/commands/addJob-8.lua, src/enums/error-codes.enum.ts, src/test/test_job.ts
In order to prevent people to create a job when the parent does not exist
=> fix(add-job): throw error when missing parent key

docs/gitbook/guide/retrying-failing-jobs.md
Increase the awareness of needing at least one QueueScheduler instance if you want to retry a job.
=> Update docs on retrying failed jobs.

src/classes/redis-connection.ts, tests/test_connection.ts
noeviction maxmemory-policy is the only option allowed
BREAKING CHANGE: noeviction maxmemory-policy is the only option allowed
re #921
=> fix(connection): throw error when no noeviction policy

src/classes/queue-getters.ts, src/classes/worker.ts, src/interfaces/worker-options.ts, tests/test_worker.ts
separate queueName from worker name
BREAKING CHANGE: name property is renamed to queueName and name is passed into opts
fix #456
=> feat(worker): save worker name into client

src/classes/child-pool.ts, src/classes/master.ts
Fixes #956.
Throwing an exception from within the uncaughException handler just results in this handler being called again, so kind of an infinite loop. Furthermore, since the process is in an errored state forever, all jobs ending in this process will fail one after another.
=> fix(sandbox): exit uncaughtException instead of throwing error

src/classes/worker.ts
=> fix(worker): blockTime must be integer on older Redis

src/classes/queue-getters.ts, tests/test_getters.ts
if you don't provide `type` to `getJobCountByTypes` get an error would be thrown.
```bash
TypeError: Reduce of empty array with no initial value
```
I guess we can validate the parameters. but in `getJobCount` if you don't provide `type` an empty object is returned. so I guess this patch is acceptable.
=> Fix reduce initial value

src/classes/job.ts, src/classes/scripts.ts, src/commands/includes/batches.lua, src/commands/updateData-1.lua, src/commands/updateProgress-2.lua, tests/test_job.ts
We should throw an error when updating data of a job that was removed
=> fix(update): throw error when missing job key

src/classes/job.ts
updates the documentation of the method to match the actual behavior, which returns a rejected promise when job failes. 
closes #1031
=> docs: update documentation of waitUntillFinished to match behavior

docs/gitbook/guide/workers.md, docs/gitbook/guide/workers/README.md, docs/gitbook/patterns/failing-fast-when-redis-is-down.md, docs/gitbook/patterns/flows.md, docs/gitbook/patterns/idempotent-jobs.md, docs/gitbook/patterns/manually-fetching-jobs.md, docs/gitbook/patterns/throttle-jobs.md, tests/test_job.ts, tests/test_obliterate.ts
fixes https://github.com/taskforcesh/bullmq/issues/1038
=> docs(worker): specify error parameter in failed event

src/classes/flow-producer.ts, src/interfaces/flow-job.ts, tests/test_flow.ts
This PR allows to add parent opts for a root job in a flow, it makes sense only allow this for the first parent job since children are concatenated into their parents so children should not have this option, this option is generated by add flow method.
=> Feat parent opts in root job for a flow

docs/gitbook/guide/jobs/prioritized.md
Note that jobs without priority are processed last. This is not what I had assumed, so it's better to clarify it.
=> [Docs] Clarify jobs priority

src/classes/queue.ts, src/classes/repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/1151
=> fix(queue): close repeat connection when calling close

src/interfaces/backoff-options.ts
Currently, the `type` field is typed to `string` which makes it hard for users to know which values
work out-of-the-box without consulting the online documentation. This change fixes that by improving
the discoverability of the framework-defined backoff types while typing. Moreover, users will better
understand what values are supported by looking at the type definition file without having to leave
the IDE.
=> refactor(backoffoptions): improved IntelliSense for backoff types

src/classes/job.ts
=> fix: remove Error from Promise return in moveToWaitingChildren

package.json, src/classes/redis-connection.ts, tests/test_connection.ts, tests/test_obliterate.ts, yarn.lock
fixes https://github.com/taskforcesh/bullmq/issues/1193
=> fix(cluster): check correct Upstash host

src/classes/worker.ts, tests/test_getters.ts
fixes https://github.com/taskforcesh/bullmq/issues/1254
=> fix(get-workers): use blockingConnection to set clientName

src/classes/queue.ts
Currently the Queue.addBulk method's return type is incorrectly typed as
```ts
Promise<Job<DataType, DataType, NameType>[]>
```
Where it should be typed as 
```ts
Promise<Job<DataType, ResultType, NameType>[]>
```
=> Fix the Queue.addBulk return signature

src/classes/child-processor.ts
Hi,
I found that bull adds to Error prototype method toJSON() to allow proper stringify of errors. But that global change causes some problems in my implementation of error handling and returning errors to the browser.
In my express error handler I'm checking if method `toJSON()` exists (that exists in my custom error's class), and then return result to browser.
```
const errorDetails = 'toJSON' in err ? err.toJSON() : {
msg: err.message
};
res.json(errorDetails);
```
Normally, any non-custom error is pushed to the browser with `msg` field only. But when something wrong happens inside bullmq processing, it is returned to `toJSON` method and for example stack trace is visible in browser (err.stack is in Error.prototype so it is returned by bull's custom toJSON method).
My PR adds custom …
=> Define custom name for toJSON method

src/classes/queue.ts, src/interfaces/jobs-options.ts, src/interfaces/queue-options.ts
=> fix(queue): get rid of repeat options from default

src/classes/worker.ts
One easy way to fix this: https://github.com/taskforcesh/bullmq/issues/1294
Please advise if there is any better way.
=> fix: avoid calling delay() if queue is being closed

README.md
The example in the Readme contains incorrect typescript. The `string` types are actually used like destructuring here.
=> Readme: Fixed incorrect typescript example

package.json, src/classes/flow-producer.ts, src/classes/job.ts, src/classes/queue-events.ts, src/classes/queue-getters.ts, src/classes/queue-scheduler.ts, src/classes/redis-connection.ts, src/classes/worker.ts, tests/test_connection.ts, yarn.lock
imo this is a relatively non-breaking split-out from https://github.com/taskforcesh/bullmq/pull/1346
- the ioredis commands are now uppercased (typed)
- the return type for multi.exec() changed, so it returns unknown instead of any. hence I needed to do some typecasts there.
- removed test "when using redisOptions" and the code it was testing, as IORedis no longer accepts that parameter
closes https://github.com/taskforcesh/bullmq/issues/1332
=> chore: upgrade to ioredis 5

.github/workflows/test.yml, .gitignore, package.json
- uses coveralls github action to submit coverage
- sets nyc limits to realistic values
- adds a check how much a PR lowered the coverage
you can see it in action [here](https://github.com/boredland/bullmq/pull/14).
=> ci: set up nyc coverage limits and coveralls action

package.json
split out from https://github.com/taskforcesh/bullmq/pull/1346
imo this should not be a breaking change, even though exports is only supported since node12(?), as for older node versions the `main` export remains. keep in mind that this still wont be fully esm compatible, as get-port and ioredis will be still be on non-esm versions.
contributes to https://github.com/taskforcesh/bullmq/issues/201
=> chore: allow esm imports through exports field

src/classes/compat.ts
while browsing the files I saw those generics were not used at all and hence pretty useless. I suppose this is what they were supposed to do.
split out from https://github.com/taskforcesh/bullmq/pull/1346
=> chore: use some unused types properly

package.json, src/classes/child-pool.ts, src/types/net.d.ts, yarn.lock
... without deprecating node12.
In the light of https://github.com/taskforcesh/bullmq/pull/1346 I want to explore alternatives to deprecating node12 (for now).
reasoning: 
as per the release notes for node 12.20, node supports using the `node:` prefix in dynamic imports. my hope is, that by importing get-port dynamically, this automatically adds support for the non-dynamic `node:` imports 'inside' get-port.
I tested this using the following script (copied over from the readme) run by node12:
```js
const bullmq = require('../dist/cjs/index');
const queue = new bullmq.Queue('Paint');
queue.add('cars', { color: 'blue' });
const worker = new bullmq.Worker('Paint', async job => {
if (job.name === 'cars') {
console.log(job);
}
});
```
and I successfully tried to build a similar file (with es …
=> chore: upgrade get-port

.github/workflows/release.yml
Currently the releases seem to be stuck. I saw that phenomenon when Husky was running in CI and there are [similar](https://github.com/semantic-release/git/issues/124) [issues](https://github.com/semantic-release/git/issues/154) on the web. Perhaps explicitly disabling it does the trick?
=> ci: disable husky during release

docs/gitbook/guide/queues/README.md
I noticed this typo when reading the documentation.
=> docs: fix typo on queue

docs/gitbook/guide/jobs/delayed.md, docs/gitbook/guide/jobs/stalled.md, docs/gitbook/guide/queuescheduler.md
The html page is no longer generated by typedoc since v2
=> docs: update Queue Scheduler API Reference

package.json, src/classes/child-pool.ts, yarn.lock
Fixes #1424 by replacing the `get-port` module, which causes errors in some scenarios when imported, with a simple function that uses the built-in NodeJS `net` module to find an open port for child processes. This has been tested using [patch-package](https://www.npmjs.com/package/patch-package) in a project where sandboxed jobs were previously unable to be processed due to this issue.
=> Get open port using built-in module instead of get-port

src/classes/worker.ts
Hi, thank you for this library.
The stalled jobs timer currently prevents Node from exiting - which can take up to 30 seconds with the default configuration. This small PR uses the worker's already available `TimerManager` to clear it when the worker is `close`d, allowing Node to exit promptly.
=> fix(worker): clear stalled jobs timer when closing worker

docs/gitbook/guide/flows/README.md
While implementing jobs using the "Flows" guide i noticed a `TypeError: Object(...).values is not a function` error when using the code from the docs. Changing it to `Object.values(childrenValues)` is the correct usage.
=> docs: fix Object.values usage in flows guide

src/classes/repeat.ts
This adds a small migration step to `addNextRepeatableJob` to convert from the old `cron` key to the new `pattern` key.
Using `pattern` instead of `cron` has been supported since 1.90, but it only started being _required_ in 3.0.0. Unfortunately throughout all of 2.x, passing the `cron` key to job creation would _not_ translate it into a `pattern` key internally. This means that any repeatable jobs created between 1.90 and 3.0.0 that use the `cron` key instead of `pattern` will fail when upgrading to 3.0.0 with the error `Validation error, cannot resolve alias "und"`. This patch aims to smooth out that transition by silently migrating any existing jobs with a `repeat.cron` key to instead have `repeat.pattern`.
For maximum compatibility this patch should stick around until at least v4.0.0.
=> fix(repeat): allow easy migration from bullmq <3 to >=3

src/classes/job.ts, tests/test_queue.ts
ref https://github.com/taskforcesh/bullmq/pull/1556, in next breaking change we can restore throwing the error to avoid this edge case
=> fix(job): console warn custom job ids when they represent integers

src/classes/worker.ts
It is useful to have a different token per worker processing "task", as well as a token based on the worker id, so that we can have a better mapping between jobs and workers in the future.
=> fix(worker): add token postfix

src/classes/queue-getters.ts, src/classes/scripts.ts, src/commands/getRanges-1.lua, tests/test_getters.ts
fixes https://github.com/taskforcesh/bullmq/issues/1546
=> fix(get-jobs): filter marker

src/classes/job.ts, src/classes/scripts.ts, src/commands/moveToFinished-12.lua, tests/test_flow.ts
When creating a flow with a long-running job in the beginning (e.g. takes multiple seconds) and during the processing of the job you want to add a new parent to this job (because it should run after the long-running job) it doesn't execute the job which was added after.
The root cause of this issue is, that the worker fetches the `Job` from redis before it moves it to active. When the `Job` then finishes, the worker passes the previous fetched instance of the job to `moveToCompleted`. When an additional Job is added as `parent` of the current processing job, it never gets executed because the instance doesn't have the correct parent key. 
This PR adds an additional "sync" of the parent key of the job before it gets moved to completed to have the current instance up to date when in the …
=> fix(job): fetch parent before job moves to complete

src/commands/includes/removeJobFromAnyState.lua, tests/test_job.ts
This optimization of the `removeJobFromAnyState.lua` script makes removing jobs a **lot** faster.
Fixes #1603
=> fix #1603: Fix performance issues in `remove()`

src/classes/redis-connection.ts
As stated in https://github.com/taskforcesh/bullmq/pull/1440 it should be a warning, not an error.
=> fix(connection): apply console.warn in noeviction message

docs/gitbook/guide/connections.md
This PR makes the `keyPrefix` warning message more pronounced, as that can cause incredibly hard to track down issues.
I would also suggest that BullMQ checks if the `keyPrefix` key is set and crashes out if it is, as this is a critical error on the user part, but this PR does not cover that case.
=> docs: make keyPrefix warning more pronounced

src/classes/child-pool.ts
Resolves #1587
This issue has been interfering with my work so I decided to investigate the issue and submit a patch back to the community. Great work @manast @roggervalf on the library!
Infinite worker processes would spawn for invalid worker JS file. (i.e. default export not reachable)
Some examples how this could unintentionally happen:
```js
// worker.js
// Example 1: Library that throws an error for whatever reason
const lib = require("mylib")
// Example 2: Typo/SyntaxError in the file (usually happens in development)
constmyVar = 3; // ReferenceError constmyVar doesn't exist (need space between const keyword and var name)
module.exports = () => {
// Worker implementation
}
```
**Case 1 (error thrown inside module.exports fn)**
1. BullMQ sends "Failed" signal from …
=> fix: infinite worker process spawned for invalid JS file

python/bullmq/scripts.py
This PR fixes two wrong types in the `Scripts.array2obj` method.
The previous version raised two errors, the first with the `arr` parameter with the following:
```
List expression not allowed in type annotation
Use List[T] to indicate a list type or Union[T1, T2] to indicate a union type
```
And the second on the return type `{str: str}` failing with the following:
```
Dictionary expression not allowed in type annotation
Use Dict[T1, T2] to indicate a dictionary type
```
The `List` and `Dict` types are deprecated since version [3.9](https://peps.python.org/pep-0585/), so I used `list` and `dict` as the rest of codebase
=> fix(python scripts): fix typing on array2obj function

python/bullmq/queue.py, python/bullmq/scripts.py
This PR replaces the all string concatenation in the python folder with string formatting with the `f""` literal.
They were introduced in [python 3.6](https://peps.python.org/pep-0498/) so there shouldn't be any compatibility issue with oldest interpreters.
Also, formatted string have been seen to perform better than string concatenation, and they are also more easily to read.
=> refactor(python): replace string concatenation with string formatting

python/bullmq/job.py, python/bullmq/worker.py
This PR follows #1795, adding the typed dict `JobOptions` class for the python class `Job`.
In the previous, I forgot to add `total=False` to the `WorkerOptions` class, so I added it here. Sorry!
Please tell me if it is better to move these typed dict classes in a subfolder like `types` or something, since these types will grown once the python library will add more things to match the node version
=> chore(python job): add JobOptions

python/bullmq/queue.py
This PR follows #1797 and #1796, adding the typed dict class `JobOptions` to the `add` method of the `Queue` class
=> chore(python queue): add JobOptions to add method

python/bullmq/job.py, python/bullmq/queue.py, python/bullmq/worker.py
The current implementation is always halting the Worker loop right after the first processed message. It is happening bc this small Python or/and precedence issue. After the fix, the Worker will keep processing messages till it's explicitly closed.
=> Turning into an "always waiting" worker

docs/gitbook/bull/patterns/persistent-connections.md
Fixed a minor spelling error in the persistent connections documentation page ('automatiacally' -> 'automatically').
=> docs: fix typo in persistent connections page

python/bullmq/scripts.py
Please, in Python you should not compare `True` and `False` with the `is` operator. 
You can find recomendations for this in the [PEP 8](https://peps.python.org/pep-0008/#programming-recommendations).
> Don’t compare boolean values to True or False using ==:
> 
> Correct:
> ```py
> if greeting:
> ```
> 
> Wrong:
> ```py
> if greeting == True:
> ```
> Worse:
> ```py
> if greeting is True:
> ```
=> chore(python): replace is operator

docs/gitbook/guide/jobs/delayed.md
Related: #1815
Fixed type issue in scheduled job example code (works in JS due to coercion, but not TS with sufficiently strict config).
=> docs: fix type error in scheduled job example code

python/bullmq/worker.py
This PR updates the return type of `getCompleted` since it was incorrectly typed as `[List[Job], List]`
=> refactor(python): update getCompleted return type

src/classes/redis-connection.ts, tests/test_connection.ts
Upstash is currently rolling out redis streams to all remaining regions and will be compatible with bullmq.
This draft is just a preparation for when the time comes.
Please let me know if you're happy with these changes.
=> feat(upstash): don't throw an error when detecting an upstash host

python/bullmq/queue.py, python/bullmq/redis_connection.py, python/bullmq/worker.py
Like `BullMQ` for typescript, we can pass the connection options of the Redis as string.
- [Reference for redis.from_url](https://redis-py.readthedocs.io/en/stable/connections.html#redis.Redis.from_url)
=> feat(python): accept redis options as string

python/bullmq/job.py, python/bullmq/queue.py, python/bullmq/scripts.py, python/bullmq/types/__init__.py, python/bullmq/types/job_options.py, python/bullmq/types/keep_jobs.py, python/bullmq/types/queue_options.py, python/bullmq/types/retry_job_options.py, python/bullmq/types/worker_options.py, python/bullmq/worker.py
This PR moves the first types we introduced into a subfolder called `types`.
I used the name `types` and not `typing` since python already has a builtin library called `typing`.
Sure, we could just do `bullmq.typing`, I don't have any strong opinion about this, feel free to tell me if you think another name will be better.
=> chore(python): move types into a subfolder

src/classes/child.ts
As of the [3.13.2](https://github.com/taskforcesh/bullmq/releases/tag/v3.13.2), this library no longer builds when using `@types/node` version >= `13.6` due to removed support for importing `EventEmitter` via default export.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41353#issuecomment-579381008 for more details
This PR fixes this by importing via named export instead of default export.
=> fix(worker): use named import

src/classes/worker.ts, tests/test_job.ts, tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/1914
=> test(job): do not save stacktrace when job key is missing

python/setup.py
When installing version 4.0.1 on freshly configured python virtual environment, and when attempting to import bullmq module, I've noticed error message:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/mtodoric/dev-in-progress/fapi_esalertmanager/esam_test/lib/python3.10/site-packages/bullmq/__init__.py", line 10, in <module>
from bullmq.queue import Queue
File "/home/mtodoric/dev-in-progress/fapi_esalertmanager/esam_test/lib/python3.10/site-packages/bullmq/queue.py", line 3, in <module>
from bullmq.scripts import Scripts
File "/home/mtodoric/dev-in-progress/fapi_esalertmanager/esam_test/lib/python3.10/site-packages/bullmq/scripts.py", line 9, in <module>
from bullmq.utils import isRedisVersionLowerThan
File …
```
=> Fix 'install_requires' to include semver

.madgerc, src/classes/job.ts
We were debugging this for around 3 days, for us to find out that `Queue`, which extends `MinimalQueue`, does not work and only `QueueEvents` does. 
You can also refer to your documentation: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.job.waituntilfinished.md
=> fix: type of queueEvents for waitUntilFinished

src/classes/job.ts
Following recently merged https://github.com/taskforcesh/bullmq/pull/1958
There is a path alias config in the `tsconfig.json` that make the alias work for the typescript compiler. However the output will still contain the alias and it breaks the import.
see this [SO](https://stackoverflow.com/questions/43324209/typescript-do-not-replace-non-relative-paths-defined-in-tsconfig) for another example
=> Fix queue-events import in Job

src/classes/redis-connection.ts
In the latest version redisVersion is needed in worker.ts, this PR move the setter of RedisConnection.version in init outside the if.
=> fix(issue 1988): set redisVersion

python/bullmq/scripts.py, python/bullmq/worker.py, python/tests/worker_tests.py
fixes https://github.com/taskforcesh/bullmq/issues/2063
=> fix(python): respect concurrency in worker

.github/workflows/release.yml, python/pyproject.toml, python/requirements.txt
Reverts taskforcesh/bullmq#2074
Wait for this issue https://github.com/python-semantic-release/python-semantic-release/issues/645 and https://github.com/python-semantic-release/python-semantic-release/issues/652 to be fixed
=> chore(python): revert upgrade semver to prevent warnings

python/bullmq/redis_connection.py
This change adds username option to redisOpts. currently, you're unable to set a custom username for the Redis connection.
=> feat: add username option to redisOpts

python/bullmq/job.py
function getReturnValue() for json loading the string returnvalue from a completed Job is not returning the value
=> fix(python): job getReturnValue not returning returnvalue

package.json, yarn.lock
use these new features:
https://github.com/conventional-changelog/conventional-changelog/pull/1063
https://github.com/conventional-changelog/conventional-changelog/pull/1064
=> ci(semantic-release): ignore python commits

src/classes/worker.ts, tests/test_worker.ts
I got hinted that if you use NaN as a concurrency value the worker goes bananas. Here is a fix for it.
=> fix(worker): throw exception with NaN as concurrency

src/classes/child.ts
Import commands from their originating module, not from a re-export module.
This is important for compatibility with import-in-the-middle and other import-altering code, otherwise this results in a partially-loaded module being passed into instrumentation code.
=> Avoid importing from '..'

docs/gitbook/guide/jobs/prioritized.md
Jobs without a priority assigned now have the most priority, not the least. This PR updates the documentation to reflect that.
Reference: https://bullmq.io/news/062123/faster-priority-jobs/
=> docs(prioritized.md): fix doc regarding jobs without a priority assigned

src/classes/worker.ts
Hi,
It seems that #2149 missed a spot when passing around this flag, as workers still emit this warning even with a true flag.
=> fix: forward skipVersionCheck to blockingConnection

src/commands/includes/removeZSetJobs.lua
The `drain-4` command used in the `queue.drain()` function still used a non-batching variant of the `unpack` function in the `removeZSetJobs.lua` file. This resulted in the drain function failing when the unpack had too many values to unpack. 
This PR adds a range to the unpack function so that it has to unpack fewer values for each batched iteration.
=> fix:Batched unpack now uses range

.github/workflows/release.yml, python/bullmq/scripts.py, python/tests/worker_tests.py
fixes https://github.com/taskforcesh/bullmq/issues/2196
=> fix(move-to-finished): stringify any return value [python]

docs/gitbook/python/introduction.md
`job_token` is a required parameter for the process function otherwise the function breaks. 
Another solution would be to use `*args` but I am not sure if it's worth being in the documentation
=> fix(python): introduction doc

docs/gitbook/bullmq-pro/changelog.md, src/classes/child-processor.ts, src/interfaces/sandboxed-job.ts, tests/fixtures/fixture_processor_update_progress.js, tests/test_sandboxed_process.ts
fixes https://github.com/taskforcesh/bullmq/issues/2213
=> fix(sandbox): update progress value on job instance

docs/gitbook/bullmq-pro/groups/rate-limiting.md
There was a `:` missing in this example
=> fix key typo in rate limit example

src/classes/queue-base.ts, src/classes/worker.ts, tests/test_worker.ts
=> fix(worker): keep extending locks while closing workers

python/bullmq/backoffs.py, python/tests/worker_tests.py
When a builtin backoff type is used, the lookup was expecting and object with a property type, but the passed value from the job is a dict. This fixes the lookup and adds a test for it.
Before the fix, an exception would be thrown: 
```
Error moving job to failed 'dict' object has no attribute 'type'
```
=> fix(python backoff): fix bug when using builtin backoff type

src/utils.ts
This pull request addresses a TypeScript error where `EventEmitter` was incorrectly used as a namespace rather than a type.
- Updated imports to use `EventEmitter` as a type instead of a namespace.
- Ensured that all instances where `EventEmitter` is used are consistent with TypeScript's type usage standards.
- Resolves the TypeScript compilation error.
Attached is a screenshot highlighting the TypeScript error and the corrected code:
```
"dependencies": {
"@fastify/static": "^6.10.2",
"@nestjs/bullmq": "^10.0.1",
"@nestjs/common": "^10.1.3",
"@nestjs/config": "^3.0.0",
"@nestjs/core": "^10.1.3",
"@nestjs/jwt": "^10.1.0",
"@nestjs/mongoose": "^10.0.1",
"@nestjs/passport": "^10.0.0",
"@nestjs/platform-express": "^10.1.3",
"@nestjs/platform-fastify": "^10.1.3",
"@nestjs/schedule": "^3.0.2", …
```
=> fix(utils): use EventEmitter as a type instead of a namespace to resolve type error

src/classes/worker.ts, src/utils.ts, tests/test_worker.ts
=> fix(worker): get dirname by using module.filename

docs/gitbook/SUMMARY.md, docs/gitbook/bull/patterns/redis-cluster.md, docs/gitbook/guide/redis-tm-hosting/README.md, docs/gitbook/guide/redis-tm-hosting/aws-elasticache.md, docs/gitbook/guide/redis-tm-hosting/aws-memorydb.md, docs/gitbook/patterns/redis-cluster.md, python/bullmq/queue.py, python/bullmq/types/queue_options.py
Currently the NodeJS version has the same connection arguments for the worker and queue whereas python as two different format.
It's a breaking change but using the same format might prevent bugs in the future
=> fix(python): uniyfing redis connection args for Queue and Worker

src/classes/flow-producer.ts, src/classes/queue-base.ts
I noticed that the flow producer wasn't closing correctly which was leading to my application crashing when passing the flow Redis connection options.
After making the following changes, the flow can now close nicely.
=> fix(flows): update constructor and methods to match queue base

src/classes/redis-connection.ts, src/classes/worker.ts, tests/test_connection.ts
Fixes https://github.com/taskforcesh/bullmq/discussions/372
=> fix(worker): fix so that worker can be closed if Redis is down

tests/test_job.ts
ref https://github.com/taskforcesh/bullmq/issues/2356
=> test(job): add case when using custom error

docs/gitbook/SUMMARY.md
The `removeDependencyOnFailure` option added in #1953 is hard to find, it seems the documentation is not publicly linked.
This PR suggests to add it to *Gitbook Summary* same as its siblings.
=> Add link to Gitbook Summary for flows/remove-dependency.md

src/classes/scripts.ts, src/commands/moveJobFromActiveToWait-10.lua, tests/test_rate_limiter.ts
When returning a rate limit error we must move the job from active to wait, independently of the ttl value, in case we don't move , the job will get stalled or could fail if we have maxStalledCount as 0
=> fix(rate-limit): move job to wait even if ttl is 0

src/commands/includes/addDelayMarkerIfNeeded.lua, tests/test_job.ts
a marker from a delayed job could override an existing marker from a standard job as both have the same member value, that cause that a worker picks the marker thinking that all the remaining jobs are in delayed status, so it wait the delay even having standard jobs. In order to avoid that we can just use a different member value for the delayed jobs and bzpopmin will pick the lower value (standard marker "0" with score 0) later it could pick marker "1" with delayed score
=> fix(marker): differentiate standard and delayed markers

python/bullmq/error_code.py, python/bullmq/scripts.py, src/classes/scripts.ts, src/commands/addDelayedJob-6.lua, src/commands/addParentJob-4.lua, src/commands/addPrioritizedJob-7.lua, src/commands/addStandardJob-7.lua, src/commands/includes/handleDuplicatedJob.lua, src/enums/error-code.ts, tests/test_flow.ts
while adding a duplicated job, we can replace the parent job if this job had one, while replacing a parent value, we will end with an orphan parent, we must throw an error in this case
=> fix(flow): parent job cannot be replaced

docs/gitbook/SUMMARY.md, docs/gitbook/guide/flows/ignore-dependency.md, src/classes/job.ts, src/classes/scripts.ts, src/commands/includes/removeJob.lua, src/commands/includes/removeJobKeys.lua, src/commands/includes/removeParentDependencyKey.lua, src/commands/moveToFinished-14.lua, src/commands/removeJob-1.lua, src/types/job-options.ts, tests/test_flow.ts
ref https://github.com/taskforcesh/bullmq/issues/2092 https://github.com/taskforcesh/bullmq/issues/800
=> feat(flow): add ignoreDependencyOnFailure option

src/classes/job.ts, src/classes/queue-events.ts, src/classes/queue-getters.ts, src/classes/scripts.ts, src/classes/worker.ts, src/commands/includes/prepareJobForProcessing.lua, src/interfaces/job-json.ts, src/interfaces/worker-options.ts, src/utils.ts, tests/test_getters.ts, tests/test_worker.ts
This PR adds a new optional property to jobs, processedBy, as well as the possibility to pass a unique name to the workers. This allows to create a mapping between processed jobs and the workers that actually processed them. Furthermore, a new "rawname" property is added to the data structure returned by ```getWorkers``` that includes the worker name.
=> feat(worker): add support for naming workers

package.json, src/commands/script-loader.ts, yarn.lock
Since newest versions of "glob" are only compatible with "type": "module" which is basically imposible to enable in this repo, this PR replaces it by fast-glob.
=> fix(deps): replaced glob by fast-glob due to security advisory

python/bullmq/redis_connection.py
fix the issue when initializing connection with "ssl": True
=> fix(python): accept all parameters for redis connection

src/classes/job.ts, tests/test_job.ts
Changed the array slice for the stacktrace.
Resolution is verified with our BullMQ implementation (via npm link).
=> fix(job): stack trace limit (#2487)

python/bullmq/scripts.py, src/classes/scripts.ts, src/commands/includes/removeLock.lua, src/commands/includes/removeLockToken.lua, src/commands/moveToDelayed-8.lua, src/commands/moveToWaitingChildren-5.lua, src/commands/retryJob-11.lua
https://github.com/taskforcesh/bullmq/blob/master/src/commands/moveStalledJobsToWait-9.lua#L77 we will save some extra calls
=> perf(stalled): remove jobId from stalled after removing lock when moved from active

python/bullmq/redis_connection.py, python/bullmq/types/queue_options.py, python/bullmq/types/worker_options.py, python/tests/queue_tests.py, python/tests/worker_tests.py
Like `BullMQ` for typescript, support reusing the same redis connection. This is helpful in environments with caps on connection count.
=> feat(python): support reusable redis connections

src/classes/redis-connection.ts, src/classes/worker.ts, tests/test_queue.ts, tests/test_worker.ts
as this fix https://github.com/redis/redis/pull/11688 was introduced since version 7.0.8, redis users using a lower version are having issues where bzpopmin command blocks forever, this is happening because passing 0.001 is the same as using 0.
Fixes https://github.com/taskforcesh/bullmq/issues/2466
=> fix(worker): use 0.002 as minimum timeout for redis version lower than 7.0.8

python/bullmq/worker.py, src/classes/worker.ts
ref https://github.com/taskforcesh/bullmq/issues/2466
there was an issue when resolving merge conflicts from https://github.com/taskforcesh/bullmq/pull/2515/commits/917ff96d49b24ae3891005934a7d47b72c67cef1
=> fix(worker): return minimumBlockTimeout depending on redis version (python)

python/bullmq/job.py, python/bullmq/scripts.py, src/commands/moveStalledJobsToWait-9.lua, tests/test_stalled_jobs.ts
fixes https://github.com/taskforcesh/bullmq/issues/2531
=> fix(stalled): consider ignoreDependencyOnFailure option (python)

python/bullmq/redis_connection.py
As you can see in the [redis-py docs](https://redis.readthedocs.io/en/stable/backoff.html#redis.backoff.ExponentialBackoff) the `ExponentialBackoff` starts with 8**ms** and ramps up to only 512**ms**. Paired with only three retries this makes it fail very quickly.
I increased the values to start with 1**s** and ramp up to 20**s**. Also, increased the retries to 20. I think this brings it closer to the JavaScript library.
Related to my issue: #2542
=> fix(python): increase redis retry strategy backoff

src/classes/worker.ts, tests/test_worker.ts
it'll call directly moveToActive script
ref https://github.com/taskforcesh/bullmq/issues/2466
=> perf(worker): do not call bzpopmin when blockDelay is lower or equal 0

python/bullmq/worker.py
This makes the worker `close` method wait for jobs to be done processing in the python library. I think this brings it closer to the behavior of the JS library.
We have used this in production for a while and has worked out well.
=> feat(python): wait for jobs to finalize on close

src/classes/worker.ts
Potentially fix for https://github.com/taskforcesh/bullmq/issues/2552
=> fix(worker): make sure clearTimeout is always called after bzpopmin

python/bullmq/redis_connection.py
After a lot of trial and error on why connection errors don't seem to get retried (#2542), I found this to be the culprit.
You can verify it with the following script. Start running it, then kill your redis instance.
- With `redis.asyncio.retry` it will not crash and restart pinging when redis comes back
- With `redis.retry` it will crash
```python
import os
import asyncio
import redis.asyncio as aioredis
from redis.backoff import ExponentialBackoff
from redis.asyncio.retry import Retry
from redis.exceptions import (BusyLoadingError, ConnectionError, TimeoutError)
retry = Retry(ExponentialBackoff(cap=20, base=1), 20)
retry_errors = [BusyLoadingError, ConnectionError, TimeoutError]
redis_connection = aioredis.from_url(os.environ.get('REDIS_URI', 'redis://localhost:6379'), …
```
=> fix(python): use async Retry

docs/gitbook/guide/parallelism-and-concurrency.md
Looks like the author intended to write "OS processes"
=> Fixed Typo in Docs

src/classes/worker.ts
Use of .message rather than .name (introduced in https://github.com/taskforcesh/bullmq/commit/4c4559b3c678313b3727c9781a6d3f963bcfda4e) causes Sandboxed job processes to not correctly check for this error. It results in 'Missing lock for job 2. failed'.
Also created issue for this: https://github.com/taskforcesh/bullmq/issues/2566
fixes #2566
=> fix(worker): Ensure DelayedError is checked for for Sandboxed Processors

src/classes/job.ts, src/classes/worker.ts
client.multi() creates a transaction of multiple commands (all commands to exec call), to ensure atomicity of multiple commands.
As extendlock and createbulk do not require atomicity for multiple commands pipeline can be used to reduce the round trip.
=> fix: extendlock,createbulk use pipeline no multi command

src/classes/worker.ts
The custom code for performing a disconnection and reconnection was proven to cause problems, whereas the IORedis builtin worked properly in all the scenarios that we know of.  This should fix issue #2466
=> fix(worker): properly cancel blocking command during disconnections

src/classes/queue-getters.ts, src/classes/scripts.ts, src/commands/getRateLimitTtl-1.lua, tests/test_rate_limiter.ts
fixes https://github.com/taskforcesh/bullmq/issues/2628
=> fix(queue-getters): consider passing maxJobs when calling getRateLimitTtl

docs/gitbook/guide/jobs/repeatable.md, src/classes/repeat.ts, src/classes/scripts.ts, src/classes/worker.ts, src/commands/addRepeatableJob-2.lua, src/commands/obliterate-2.lua, src/commands/removeRepeatable-2.lua, src/interfaces/index.ts, src/interfaces/repeatable-job.ts, src/interfaces/repeatable-options.ts, tests/test_repeat.ts, tests/utils/repeat_utils.ts
ref https://github.com/taskforcesh/bullmq/issues/2612 fixes https://github.com/taskforcesh/bullmq/issues/2399 https://github.com/taskforcesh/bullmq/issues/2596
=> feat(repeatable): new repeatables structure

docs/gitbook/guide/metrics/metrics.md
Fixes an extra "_" in `docs/gitbook/guide/metrics/metrics.md`
=> Fix markdown typo in metrics.md

src/classes/scripts.ts, src/commands/addRepeatableJob-1.lua
fixes https://github.com/taskforcesh/bullmq/issues/2660
=> fix(repeatable): pass custom key as an args in addRepeatableJob to prevent CROSSSLOT issue

src/classes/repeat.ts, src/classes/scripts.ts, tests/test_repeat.ts
fixes https://github.com/taskforcesh/bullmq/issues/2661
=> fix(repeatable): consider removing legacy repeatable job

docs/gitbook/bullmq-pro/changelog.md, docs/gitbook/changelog.md, tests/test_clean.ts
marker key is a temporal key, as soon as a worker returns the last job, this key could be consumed very fast
=> test: fix flaky test

python/bullmq/job.py, python/bullmq/scripts.py, python/tests/job_tests.py, python/tests/worker_tests.py
The Python version can return a non-JSON-compliant value to Redis, which breaks when trying to retrieve the value using the Node version of the library.
By adding "allow_nan=True", we raise an error before sending the value to Redis, which prevents having bad JSON in the job's return value.
=> fix(python): make sure json.dumps return JSON compliant JSON (python)

src/classes/worker.ts
while a queue is rate limited we can be able to promote delayed jobs ref https://github.com/taskforcesh/bullmq/discussions/2582
=> perf(worker): promote delayed jobs while queue is rate limited

src/classes/job.ts, src/commands/includes/moveParentFromWaitingChildrenToFailed.lua, src/commands/moveToFinished-14.lua, tests/test_flow.ts, tests/test_getters.ts, tests/test_job.ts
our current behavior keeps parent in waiting-children state when regular children fail, instead we should fail parent directly as regular children must be considered as hard dependencies. For soft dependencies we have other options like removeDependencyOnFailure or ignoreDependencyOnFailure.
fixes https://github.com/taskforcesh/bullmq/issues/800
=> fix(flow): fail parent on failure by default

src/classes/job.ts
ref https://github.com/taskforcesh/bullmq/pull/2342
=> fix(job): change moveToFinished return type to reflect jobData

src/commands/moveStalledJobsToWait-9.lua, tests/test_stalled_jobs.ts
Missing the case where removeDependencyOnFailure option is provided
=> fix(stalled): support removeDependencyOnFailure option when job is stalled

src/classes/scripts.ts, src/commands/includes/moveParentFromWaitingChildrenToFailed.lua, tests/test_flow.ts
We are missing to handle this option when a grandchild fails with failParentOnFailure, then if a parent has ignoreDependencyOnFailure we should consider this case.
=> fix(flow): recursive ignoreDependencyOnFailure option

src/classes/repeat.ts
pattern is the only option that must be used instead of cron
=> fix(repeat): remove legacy cron option

docs/gitbook/changelog.md, docs/gitbook/python/introduction.md
fixes https://github.com/taskforcesh/bullmq/pull/2695
=> docs(connection): add decode_responses warning [python]

src/commands/includes/collectMetrics.lua
don't need to save more zeros than max data points
=> perf(metrics): save zeros as much as max data points

src/classes/redis-connection.ts, src/interfaces/redis-options.ts, tests/test_connection.ts
Allow option to use/pass connection URL into ioredis directly without having to create connection manually and consequently maintaining it, fixes #1220.
It does not intentionally parse the url (as per #1220 requirement) and delegates URL parsing to ioredis using appropriate constructor. Thus added tests only check established connections, leaving rest up to ioredis.
=> fix(connection): allow passing connection string into IORedis

src/commands/addRepeatableJob-2.lua, tests/test_job.ts
fixes https://github.com/taskforcesh/bullmq/issues/2744 as if a repeatable job is promoted and it's not removed after completion, we can readd same repeatable. This operation removes current delayed job, but after that we are adding a delayed job that have the same jobId, as a duplicate we just ignore to add a new delayed instance. We should validate that this job exists before removing it. ref https://github.com/taskforcesh/bullmq/pull/2776
=> fix(repeatable): avoid delayed job deletion if next job already existed

src/classes/queue.ts
Added a clarification regarding the grace period for `Queue.clean()`.
=> Update Queue.clean() documentation

.github/workflows/test.yml
Valkey is a new alternative to Redis: https://valkey.io with an open source license.
=> ci: add tests for valkey

src/classes/child-pool.ts, src/classes/sandbox.ts, tests/test_child-pool.ts, tests/test_sandboxed_process.ts
When exit errors happened too soon, promises were never resolved. This PR prevents that behavior.
=> fix(sandbox): catch exit errors

tests/test_job_scheduler.ts
Proves that there is no issue here: https://github.com/taskforcesh/bullmq/issues/1606
=> test: starts immediately after remove job scheduler

src/classes/job.ts, src/classes/scripts.ts, src/commands/includes/deduplicateJob.lua, src/interfaces/base-job-options.ts, src/utils.ts, tests/test_job.ts, tests/test_job_scheduler.ts, tests/test_repeat.ts
ref https://github.com/taskforcesh/bullmq/issues/2801
=> feat(job): expose priority value

src/classes/job-scheduler.ts, src/classes/job.ts, src/classes/scripts.ts, src/interfaces/repeat-options.ts, tests/test_job_scheduler.ts
This PR set the immediately option in the job scheduler as deprecated. Immediately has been a hack in its introduction, to mitigate the way "every" works, which in some cases can result in an undesired behaviour if the "every" setting is a large amount of time, lets say one month, the jobs could not be produced until many days or in worst case scenario 29 days had passed. With this PR however, immediately becomes the standard. This is a small breaking change that we hope will not affect any users, specially as this only affects the recently added "upsertJobScheduler". I think it is a good trade-off instead of having to wait for a major version.
=> feat(repeat): deprecate immediately on job scheduler

src/utils.ts, tests/fixtures/fixture_processor_fail_with_circular_reference.js, tests/test_sandboxed_process.ts
ref https://github.com/taskforcesh/bullmq/pull/2813
=> fix(sandbox): fix serialization of error with circular references are present

src/classes/job.ts, src/classes/redis-connection.ts, src/classes/scripts.ts
If you share a Redis connection between different queues and you happen to use different versions of BullMQ, then you may be using incompatible Lua scripts, as the last loaded script wins, replacing the previously loaded one. Note that this is only a problem if 1) you are reusing a ioredis connection, and 2) you are mixing different versions of the BullMQ library, in other words, not very common in most scenarios, but this PR fixes the issue by appending a version number to every command name.
=> fix(redis): use version for naming loaded lua scripts

docs/gitbook/guide/connections.md
[connection docs](https://docs.bullmq.io/guide/connections) have a link leading to a 404.
=> docs: fix broken link to commonRedisOptions keyPrefix

python/bullmq/job.py, python/bullmq/utils.py, python/tests/flow_tests.py, python/tests/job_tests.py
Adds getChildrenValues method to the Python package's Job class, used to query returning values of child jobs
=> feat(python): add Job.getChildrenValues

docs/gitbook/guide/jobs/job-ids.md
This adds a clarification to the docs that Job Id scoping is per queue, not globally.
We came across this question in a recent PR in one of our apps and research in the docs yielded no clear explanation, which required us to dig into the code and actually experiment with it, so I thought it was worth a contribution.
=> docs(job): clarify per-queue scoping of Job Ids

src/classes/job-scheduler.ts, src/classes/queue.ts, src/interfaces/repeatable-job.ts, tests/test_job_scheduler.ts
ref https://github.com/taskforcesh/bullmq/issues/2875
=> feat(scheduler): add getJobScheduler method

src/classes/redis-connection.ts
version won't be the same in pro version, when extending connection we can override it
=> fix(connection): set version as protected attribute for extension

src/classes/queue-base.ts, src/classes/queue-events.ts, src/classes/queue.ts, src/interfaces/queue-options.ts, tests/test_connection.ts
blockingConnection is an internal property that must not be overwritten by users
=> fix(connection): do not allow to set blockingConnection option

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [BullMQ Guru](https://gurubase.io/g/bullmq) to Gurubase. BullMQ Guru uses the data from this repo and data from the [docs](https://docs.bullmq.io) to answer questions by leveraging the LLM.
In this PR, I showcased the "BullMQ Guru", which highlights that BullMQ now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
=> Introducing BullMQ Guru on Gurubase.io

src/utils.ts
Fixes https://github.com/taskforcesh/bullmq/issues/2894
=> fix(telemetry): do not set span on parent context if undefined

src/commands/includes/prepareJobForProcessing.lua, src/commands/moveToActive-11.lua, src/commands/moveToFinished-14.lua, tests/test_bulk.ts
fixes https://github.com/taskforcesh/bullmq/issues/2842
=> perf(marker): add base markers while consuming jobs to get workers busy

src/classes/queue.ts, src/classes/worker.ts, tests/test_worker.ts
This PR is required by packages that extend the Queue class such as BullMQ Pro so that they can customise the telemetry data when adding jobs to the queue.
=> feat(queue): refactor a protected addJob method allowing telemetry extensions

src/commands/includes/moveParentFromWaitingChildrenToFailed.lua, src/commands/includes/removeJobsOnFail.lua, src/commands/moveStalledJobsToWait-9.lua, tests/test_flow.ts
fixes https://github.com/taskforcesh/bullmq/issues/2229
=> fix(flow): allow using removeOnFail and failParentOnFailure in parents

src/classes/job.ts
Thanks for the awesome project!
Just spotted a typo via the editor intellisense and figured this would be a quick fix.
Keep up the good work :)
=> fix: typo in docstring for `moveToDelayed`

src/classes/job-scheduler.ts, src/classes/job.ts, src/classes/worker.ts, src/interfaces/job-json.ts, src/interfaces/repeat-options.ts, tests/test_job_scheduler.ts
This PR adds a guarantee for repeatable jobs based on the "every" option so that only one delayed job per job scheduler can ever be produced by making sure the next iteration is "slotted". By "slotted" we mean that we only allow the repeatable jobs for a given every setting to be placed in evenly slots in the time space. So for example, if we have an every setting of 5000 (5 seconds), then the repetition will be slotted in time 0, 5, 10, 15, 20, 25, and so on. However we also compute an offset so that we can start the iterations at the same point in time the job scheduler is added to the queue. So for instance, if we add the job scheduler at second 10:23:03 (second 3), the iterations will be slotted at 3, 8, 13, 18, and so on.
Another improvement in this PR affects retried repeatable …
=> fix: guarantee every repeatable jobs are slotted

src/commands/includes/updateJobFields.lua
Possibly fixes https://github.com/taskforcesh/bullmq/issues/2969
The theory is that in some LUA engines, empty strings are not handled like nil, but truethy instead, resulting in message pack failing trying to unpack an empty string, or maybe is that some LUA engines have a msgpack version that can unpack empty strings without crashing... in any case, better not to try to unpack empty strings.
=> fix(scripts): make sure jobs fields are not empty before unpack

src/classes/child-pool.ts, src/classes/child.ts, src/classes/sandbox.ts, tests/fixtures/fixture_processor.js, tests/fixtures/fixture_processor_exit.js, tests/test_sandboxed_process.ts
This PR solves a critical issue where a sandbox processor could get stuck in active for ever if the child process is killed when the job is in the middle of the processing.
=> fix(sandbox): fix issue where job could stay in active forever

src/classes/job.ts, tests/test_bulk.ts
1. Why is this change necessary? discard method is not working. Instead we can use UnrecoverableError
2. What problem does it solve or improve? Avoid confusion as it's not working as intended, job is not moved to failed as in bull legacy code.
3. Link to any relevant issues, if applicable.
1. How did you implement this? Add deprecated warning for now to remember to remove it in next breaking change
2. Outline the approach or steps taken.
3. List any resources or documentation that helped you.
=> refactor(job): add deprecated warning in discard method

src/classes/job-scheduler.ts, src/commands/removeJobScheduler-3.lua, tests/test_job_scheduler.ts
This PR fixes this issue: https://github.com/taskforcesh/bullmq/issues/2988
This PR makes sure that the "nextMillis" portion of every repeatable jobs is always calculated on well defined so called "time slots". The offset is only used to calculate the "delay" option of the repeatable job so that it repeats at the appropriate time, but is not used for the "nextMillis" calculation anymore.
=> fix(job-scheduler): avoid duplicates when upserting in a quick sequence

docs/gitbook/patterns/stop-retrying-jobs.md, tests/test_rate_limiter.ts
1. Why is this change necessary? We should clarify the difference between attemptMade and attemptStarted and when they can be used
1. How did you implement this? Fix example in our documentation and add a info section to clarify these concepts
ref https://github.com/taskforcesh/bullmq/issues/3000
=> docs(stop-retrying): clarify different between attemptMade and attemptsStarted

src/classes/scripts.ts, src/commands/updateJobScheduler-6.lua, src/commands/updateJobScheduler-7.lua, tests/test_job_scheduler.ts
1. Why is this change necessary? In order to only add delayed jobs while current producer matches with prevMillis
1. How did you implement this? Do this validation when updating job scheduler, comparing prevMillis with producerId
=> fix(job-scheduler): add next delayed job only when prevMillis matches with producerId

src/classes/job-scheduler.ts, src/classes/scripts.ts, src/commands/updateJobScheduler-7.lua, tests/test_job_scheduler.ts
1. Why is this change necessary? Since version v[5.31.0](https://github.com/taskforcesh/bullmq/commit/9ae31bac5bb5c1f35d59db94d2af3d6eaaec1ad3) template data is saved in job scheduler record, and since v[5.34.8](https://github.com/taskforcesh/bullmq/commit/0418cd7676e730e9ddcad00ace01adbe899e124d) this same data is used for saving the next delayed job that is produced by a job scheduler. If someone migrates to v5.34.8 or a greater version, without recreating their job scheduler, next delayed jobs won't get data information.
1. How did you implement this? Pass delayed job data when updating a job scheduler, if no data is saved as template, reuse data from previous delayed job
fixes https://github.com/taskforcesh/bullmq/issues/3009
=> fix(job-scheduler): use delayed job data when template data is not present

docs/gitbook/guide/jobs/deduplication.md, docs/gitbook/guide/jobs/job-ids.md, docs/gitbook/guide/queues/README.md, docs/gitbook/guide/queuescheduler.md
My company is considering implementing BullMQ and I've been fixing obvious grammer errors as I read the docs. I noticed these errors when I had to reread the sentence a couple times in order to understand it.
I used vim and `git grep`. :muscle:
=> docs: fix several grammer errors in docs

package.json, src/classes/child-processor.ts, src/classes/main-base.ts, src/classes/sandbox.ts, src/enums/child-command.ts, src/enums/parent-command.ts, src/interfaces/child-message.ts, src/interfaces/index.ts, src/interfaces/receiver.ts, tests/fixtures/fixture_processor_get_children_values.js, tests/fixtures/fixture_processor_get_children_values_child.js, tests/test_sandboxed_process.ts
This PR adds support for using getChildrenValues from sandboxes, fixes https://github.com/taskforcesh/bullmq/issues/1306, https://github.com/taskforcesh/bullmq/issues/753, https://github.com/taskforcesh/bullmq-pro-support/issues/21 supersedes https://github.com/taskforcesh/bullmq/pull/1417
Added a response mechanisms for operations that require returning values back to the child processor from the parent process.
=> feat(sandbox): add support for getChildrenValues

src/classes/worker.ts
It seems like in some edge cases BZPOPMIN is issued after the closing procedure starts which in some backend like DragonFly can cause a longer time to actually close the worker which leads to some tests timing out.
Make sure BZPOPMIN is only called if the closing process has not started yet.
We are not 100% sure this is the cause for the timing out of some tests but still this change is needed to rule out this possibility.
=> fix(worker): avoid possible hazard in closing worker

src/classes/queue-getters.ts, tests/test_getters.ts
To provide built in support for Prometheus.
Adding a new method ```exportPrometheusMetrics``` that returns metrics in prometheus open metrics format. 
An http server must be used to provide a HTTP endpoint to be consumed by prometheus. The current export only support gauges but we could add counters as well if metrics are enabled in the queue.
=> feat(queue-getters): add prometheus exporter

docs/gitbook/guide/connections.md
1. Why is this change necessary? Provide alternative for keyPrefix option from ioredis
1. How did you implement this? Clarify this information in connections section
ref https://github.com/taskforcesh/bullmq/issues/3013
=> docs(connections): clarify the usage of prefix option instead of keyPrefix

docs/gitbook/bullmq-pro/changelog.md, docs/gitbook/changelog.md
1. Why is this change necessary? Update changelog to reflect last changes in bullmq-pro
1. How did you implement this? Update changelog file
=> docs(bullmq-pro): update changelog to v7.26.3

src/classes/scripts.ts, src/commands/includes/updateJobFields.lua, src/commands/retryJob-11.lua, src/interfaces/minimal-job.ts, tests/test_worker.ts
1. Why is this change necessary? Errors are not updated when retrying a job
1. How did you implement this? Pass right object into retryJob script and reuse updateJobFields include 
=> fix(retry-job): consider updating failures in job

src/classes/worker.ts
1. Why is this change necessary? No need to fetch need job always when moving a job to failed, need to use similar logic as we do with move to completed
1. How did you implement this? Use same logic as in move to completed
=> fix(worker): evaluate if a job needs to be fetched when moving to failed

src/classes/worker.ts, tests/test_worker.ts
1. Why is this change necessary? As part of trying to fix the processing of jobs when closing a worker. When pausing a job we don't need to wait for a promise, instead just set it as paused and stop run execution
1. How did you implement this? Remove promise from pause method and refactor resume method to re-execute run method
Notice that we wait for pending jobs in https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L954 when pausing a worker by default, but we can possibly add paused promise into async queue https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L586, that means that we can get pause method hanging
=> refactor(pause): stop run execution

src/classes/worker.ts, tests/test_bulk.ts, tests/test_events.ts, tests/test_worker.ts
This change is necessary to avoid possible stalled jobs when closing a worker, since the close operation just stops processing the jobs that may be already in active status but have not yet started to be processed.
Making sure that we wait for the jobs to complete before resolving the close promise.
=> fix(worker): wait fetched jobs to be processed when closing

src/classes/queue.ts, src/commands/addDelayedJob-6.lua, src/commands/addParentJob-4.lua, src/commands/addPrioritizedJob-8.lua, src/commands/addStandardJob-8.lua, src/commands/includes/deduplicateJob.lua, src/commands/includes/getNextDelayedTimestamp.lua
1. Why is this change necessary? Remove unused prefixKey variable
1. How did you implement this? Remove it from deduplicateJob include and all references when this method is called
=> refactor(deduplicate-job): remove unused prefixKey variable

src/classes/job-scheduler.ts, tests/test_job_scheduler.ts
1. Why is this change necessary? If job scheduler does not exist, getJobScheduler method tries to split the id because of the old format of repeatable jobs. But as old format requires to have this id separated by :, we can also validate that the id does not contains :. Take in count that transformation of this data is being used for getJobSchedulers too.
1. How did you implement this? Change retuned type to undefined and when validating old format, make sure id/ key contains : before trying to transform it to old repeatable format
fixes https://github.com/taskforcesh/bullmq/issues/3062
=> fix(job-scheduler): return undefined in getJobScheduler when it does not exist

src/classes/scripts.ts, src/commands/drain-5.lua
fix crossslot error when running queue.drain() in redis cluster
replace '' key with queue.toKey('') to include hash tag
=> fix(drain): delay queuekey for redis cluster

src/classes/scripts.ts, src/classes/worker.ts, src/commands/moveToActive-11.lua, src/commands/moveToFinished-14.lua, tests/test_worker.ts
1. Why is this change necessary? processedBy attribute is not being set when moveToFinished script is called
1. How did you implement this? Pass worker name as part of options, this arg is already passed
fixes https://github.com/taskforcesh/bullmq/issues/3073
=> fix(job): set processedBy when moving job to active in moveToFinished

tests/test_getters.ts
1. Why is this change necessary? To fix a flaky test when get all workers
1. How did you implement this? Instead of waiting for ready event, use waitUntilReady method
=> test: fix flaky test when get all workers

src/classes/worker.ts
1. Why is this change necessary? When resuming a worker without a processor, instead of throwing an error. We can ignore to execute run method
1. How did you implement this? Check processor before executing run method when resuming
=> fix(worker): do not execute run method when no processor is defined when resuming

src/commands/includes/addJobWithPriority.lua, src/commands/includes/getPriorityScore.lua, src/commands/includes/promoteDelayedJobs.lua
1. Why is this change necessary? When promoting delayed jobs, instead of adding a marker per each record, we can add only one marker
1. How did you implement this? Extract add marker logic after moving jobs into wait or prioritized
=> perf(delayed): add marker once when promoting delayed jobs

tests/test_job_scheduler.ts
1. Why is this change necessary? Jobs that are generated by a job scheduler when using every, they are added to waiting state, and next iteration will be added into delayed. It can be only in one of this possible states
1. How did you implement this? Validate in test cases that delayed + waiting counts is 1
=> test(scheduler): fix flaky tests when validating job counts

src/commands/includes/getOrSetMaxEvents.lua, src/commands/includes/moveParentFromWaitingChildrenToFailed.lua, src/commands/moveStalledJobsToWait-9.lua, src/commands/moveToFinished-14.lua, tests/test_flow.ts
1. Why is this change necessary? When dynamically add children jobs, a parent can be in delayed state when failParentOnFailure is activated
1. How did you implement this? Consider delayed state when moving a parent to failed
=> fix(flow): consider delayed state when moving a parent to failed

src/commands/cleanJobsInSet-3.lua, src/commands/includes/cleanSet.lua, tests/test_clean.ts
1. Why is this change necessary? When removing failed jobs, no need to validate generated jobs being generated by job schedulers
1. How did you implement this? Check that repeat key is present when removing zset records
Fixes https://github.com/taskforcesh/bullmq/issues/3114
=> fix(scheduler): validate repeatKey is present when cleaning failed jobs

.github/workflows/test.yml, docs/gitbook/python/changelog.md, python/bullmq/flow_producer.py, python/bullmq/queue_keys.py, python/bullmq/worker.py, python/run_tests_dragonfly.sh, python/tests/bulk_tests.py, python/tests/delay_tests.py, python/tests/flow_tests.py, python/tests/job_tests.py, python/tests/queue_tests.py, python/tests/worker_tests.py
1. Why is this change necessary? When delay_until is retrieved from dragonfly, it's returned as string, we need to cast it to integer in order to prevent errors when using max method
1. How did you implement this? Cast delay_until as integer
ref https://github.com/taskforcesh/bullmq/pull/3092
=> fix(worker): cast delay_until to integer [python]

docs/gitbook/bullmq-pro/changelog.md, src/commands/addRepeatableJob-2.lua, src/commands/getState-8.lua, src/commands/getStateV2-8.lua, src/commands/includes/isJobSchedulerJob.lua, src/commands/includes/trimEvents.lua, src/commands/includes/updateExistingJobsParent.lua, src/commands/isFinished-3.lua, src/commands/updateRepeatableJobMillis-1.lua, tests/test_rate_limiter.ts
1. Why is this change necessary? Remove unnecessary false inequality validations base on https://www.lua.org/pil/2.2.html#:~:text=The%20boolean%20type%20has%20two,and%20anything%20else%20as%20true
1. How did you implement this? Remove inequality of false
=> refactor(scripts): remove unnecessary false inequality validations

src/classes/job.ts, src/interfaces/job-json.ts, tests/test_job.ts
When serializing jobs from json, the Job object is serialized with the value in opts.priority, rather than priority. These values get desynced when changing a job's priority after it has been added. Therefore, the real priority value will not be visible in the Job object. See example code below.
Deserialized priority from json. I did not add priority to the JobJson class since priority changes seemed to be propagating to redis fine, I only added it to the JobJsonRaw class.
Code to reproduce:
```ts
import { Job, Queue } from 'bullmq';
const myQueue = new Queue('myQueue');
await myQueue.add('myJob', {}, { jobId: "myJobId", priority: 10 });
let job: Job = await myQueue.getJob("myJobId");
console.log(job.priority); // returns 10
await job.changePriority({
priority: 9
}) …
```
=> fix(job): deserialize priority in fromjson

src/classes/worker.ts, tests/test_concurrency.ts, tests/test_flow.ts, tests/test_worker.ts
1. Why is this change necessary? When creating new queues in tests, need to clean them to not cause conflicts on other tests where number of keys are validated
=> test: remove keys from other queues

src/classes/job-scheduler.ts, src/classes/scripts.ts, src/commands/addJobScheduler-10.lua, src/commands/includes/addJobFromScheduler.lua, src/commands/updateJobScheduler-11.lua
1. Why is this change necessary? As part of giving support to serverless dbs
1. How did you implement this? Move addition of delayed job when updating job scheduler
=> fix(scheduler): remove multi when updating a job scheduler

src/classes/worker.ts
The current implementation of `moveStalledJobsToWait` processes failed jobs by making individual `Job.fromId` calls within a loop. This can lead to performance bottlenecks when dealing with many stalled jobs, as each job requires a separate Redis operation.
This change is necessary to:
* Reduce the number of Redis operations
* Improve memory usage by preventing large arrays of pending promises
* Enhance performance when handling stalled jobs at scale
* Implemented chunk processing for failed jobs using Promise.all
* Reduced number of Redis operations by batching job retrievals
=> perf(worker): optimize job retrieval for failed jobs in chunks

src/classes/job.ts, src/classes/scripts.ts, src/commands/getDependencyCounts-4.lua, tests/test_flow.ts
1. Why is this change necessary? getDependenciesCount is not returning number for ignored or failed child states
1. How did you implement this? Create a new script to handle these numbers that are missing
ref https://github.com/taskforcesh/bullmq/issues/3136
=> feat(job): support ignored and failed counts in getDependenciesCount

src/classes/queue-getters.ts, tests/test_getters.ts
expose global variables in prometheus export
Right now, it is not possible to identify the environment the prometheus data is extracted from. In aggregated Grafana dashboards, it makes the data impractical.
I added a `globalVariables` input in the `exportPrometheusMetrics` function
=> feat(prometheus export): expose global variables

tests/test_worker.ts
1. Why is this change necessary? test is flaky because renewal of token happens after lockRenewTime/2, in this case 1500 and delay of processing is 2000.
1. How did you implement this? Decrease processing delay to be less than 1500 and greater than lock time (1000)
=> test: fix flaky test when lock is lost

src/commands/includes/moveParentFromWaitingChildrenToFailed.lua, tests/test_flow.ts
1. Why is this change necessary? When dynamically add children jobs, a parent can be in prioritized state when failParentOnFailure is activated
1. How did you implement this? Consider prioritized state when moving a parent to failed
=> fix(flow): consider prioritized state when moving a parent to failed

src/commands/moveToFinished-14.lua, tests/test_flow.ts
1. Why is this change necessary? When parent is moved to failed, error should be saved saved, even if there are pending dependencies. As it will be moved to failed anyway, better to preserve the real error. Pending dependencies must be validated only when trying to move a parent to completed
1. How did you implement this? Before validating the quantity of pending dependencies, check that we are trying to move parent to completed
=> fix(flow): only validate pending dependencies when moving to completed

src/commands/updateJobScheduler-12.lua, tests/test_job_scheduler.ts
1. Why is this change necessary? When a job already exists and job scheduler is updated. We are missing to emit duplicated event
1. How did you implement this? Emit duplicated event only when trying to add next job scheduler and id already exists
=> fix(job-scheduler): emit duplicated event when next delayed job exists

src/commands/moveToFinished-14.lua, tests/test_flow.ts, tests/test_job.ts
1. Why is this change necessary? When a parent throws an error because it has pending dependencies, it's removing the lock first. That causes that moveToFailed throws a different error than pending dependencies, it throws error that lock is missing.
1. How did you implement this? Move pending dependencies validation before releasing lock, that way the error is properly propagated to the parent
=> fix(flow): validate pending dependencies before removing lock

src/classes/flow-producer.ts
1. This fixes a bug where the job name was getting set as the queue name in span attributes.
1. I implemented this by switching it to use the correct value.
Example in Grafana UI where the attribute is incorrectly set to the job name:
=> fix(FlowProducer): fix the queueName otel attribute when using addNode

src/classes/async-fifo-queue.ts, src/classes/child.ts, src/classes/job-scheduler.ts, src/classes/queue-base.ts, src/classes/queue-keys.ts, src/classes/repeat.ts, src/classes/worker.ts
1. Why is this change necessary? Because typeof returns a string, it won't return undefined. This pr fixes endDate presence validation
1. How did you implement this? Instead of checking that is not undefined, just check it's presence
=> fix(job-scheduler): fix endDate presence validation

docs/gitbook/README (1).md
1. typo fixed, text updated from `Job#fromId` to `Job.fromId(queue, jobId)`
=> docs(readme): typo fixed for text Job.fromId

tests/test_worker.ts
1. Why is this change necessary? Attempt to fix this flaky test that happens in dragonfly
=> test: fix flaky test where worker should start after job additions

src/classes/flow-producer.ts, tests/test_flow.ts
1. Why is this change necessary? Prefix attribute is optional when using getFlow. When this value is not provided it should use the same prefix as being passed in FlowProducer initialization
1. How did you implement this? Make sure to use default prefix by default if no prefix param is provided
=> fix(flow-producer): use FlowProducer prefix by default when calling getFlow

tests/test_clean.ts
1. Why is this change necessary? This is a flaky test, where keys could be greater than 7. Instead we can check those keys that we are interested - those related to the parent job that it's being removed
1. How did you implement this? Filter keys to only include the ones related to the parent job
=> test(clean): fix flaky test when checking keys quantity

src/classes/job.ts, src/classes/worker.ts, src/commands/includes/moveChildFromDependenciesIfNeeded.lua, src/commands/includes/moveParentToWait.lua, src/commands/includes/moveParentToWaitIfNeeded.lua, src/commands/includes/moveParentToWaitIfNoPendingDependencies.lua, src/commands/includes/updateParentDepsIfNeeded.lua, src/commands/moveStalledJobsToWait-9.lua, src/commands/moveToFinished-14.lua, src/commands/moveToWaitingChildren-8.lua, src/interfaces/job-json.ts, tests/test_clean.ts, tests/test_concurrency.ts, tests/test_connection.ts, tests/test_events.ts, tests/test_flow.ts, tests/test_job.ts, tests/test_job_scheduler_stress.ts, tests/test_queue.ts, tests/test_rate_limiter.ts, tests/test_stalled_jobs.ts, tests/test_worker.ts
1. Why is this change necessary? Instead of trying to move parent jobs recursively to failed status, a lazy failed process will be triggered. Failed parent jobs should instead be moved to be processed by the parent workers. In this way workers can also handle failed events from these jobs. This is not only more elegant and is a better design, but it is also a more scalable approach than our current implementation.
We introduce a new job internal attribute, which is called deferredFailure used to identify that a job must be moved to failed when it's eventually picked by a worker.
1. How did you implement this? 
Move parent to wait when a child with failParentOnFailure true is triggered and set deferredFailure attribute with a special error message. When the worker picks this job, it will …
=> perf(flow): change parent failure in a lazy way

src/commands/includes/moveChildFromDependenciesIfNeeded.lua, src/commands/includes/removeDeduplicationKey.lua, src/commands/includes/removeDeduplicationKeyIfNeeded.lua, src/commands/includes/removeDeduplicationKeyIfNeededOnFinalization.lua, src/commands/includes/removeDeduplicationKeyIfNeededOnRemoval.lua, src/commands/includes/removeJob.lua, src/commands/includes/removeJobWithChildren.lua, src/commands/moveStalledJobsToWait-9.lua, src/commands/moveToFinished-14.lua, src/commands/moveToWaitingChildren-8.lua, tests/test_events.ts
1. Why is this change necessary? When manual removal is used, job can remove deduplication key even if there is a new job with the same deduplication id already
1. How did you implement this? Validate that jobId being saved matches with the one that is being deleted
ref https://github.com/taskforcesh/bullmq/issues/3232
=> fix(deduplication): remove deduplication key only when jobId matches with the last one being saved

docs/gitbook/guide/flows/README.md, src/classes/flow-producer.ts, src/classes/job.ts, src/interfaces/minimal-job.ts, tests/test_flow.ts
1. Why is this change necessary? getFlorw and getDependencies methods are missing to retrieve ignored children jobs
1. How did you implement this? Add extra logic on these methods to retrieve data from jobKey:failed
ref https://github.com/taskforcesh/bullmq/issues/3213
=> feat(flow): support ignored children in getFlow and getDependencies methods

src/commands/addJobScheduler-11.lua, src/commands/includes/storeJob.lua, src/commands/moveToFinished-14.lua, src/commands/updateJobScheduler-12.lua, tests/test_job_scheduler.ts
1. Why is this change necessary? When a job scheduler is removed, we skip the validation of next delayed job existence. That means that we are not trying to remove it, we add this record back. That means that this job could exist in 2 different states (active, waiting/delayed). Another worker can take this record again while first instance is still running. That would cause a mismatch on locks
1. How did you implement this? Remove existing next delayed job even when job scheduler does not exists
ref https://github.com/taskforcesh/bullmq/issues/3197
=> fix(job-scheduler): remove next delayed job if present even if scheduler does not exist

.github/workflows/test.yml, python/pytest.ini, python/requirements.txt, python/tests/worker_test.py
1. Why is this change necessary? Instead of hanging if a test case did not resolve well, we can apply a timeout using pytest. Also this pr adds verbose logs for testing progress
1. How did you implement this? Add pytest-timeout module
=> ci: apply timeout when using pytest

python/bullmq/job.py, python/bullmq/scripts.py, python/bullmq/worker.py, python/tests/worker_test.py, tests/test_worker.ts
1. Why is this change necessary? In order to provide a way to do manual processing. moveToComplete method is not exposed in job instance
1. How did you implement this? Add moveToCompleted method in job instance and allow manual processing
=> feat(job): add moveToCompleted method [python]

src/classes/scripts.ts, src/commands/includes/moveChildFromDependenciesIfNeeded.lua, src/commands/includes/moveParentToWait.lua, src/commands/moveToFinished-14.lua, src/enums/error-code.ts, tests/test_flow.ts
1. Why is this change necessary? When a parent is moved to completed, failed children are ignored. That cause that a parent could be completed when a hard dependency failed. This is wrong as a parent should moved to failed in this situation
1. How did you implement this? Validate that there are no unsuccessful children before trying to move it to completed
=> fix(flow): add new error code when parent has failed children

src/classes/child-processor.ts, src/classes/sandbox.ts, src/enums/child-command.ts, src/enums/parent-command.ts, tests/fixtures/fixture_processor_get_children_failures.js, tests/fixtures/fixture_processor_get_children_failures_child.js, tests/test_sandboxed_process.ts
The wrapper is missing a couple of functions that exist on the job when it is not sandboxed. This PR tries to add one missing wrapper: `job.getIgnoredChildrenFailures()`
- Add missing wrapper
- Add child/parent commands
- Add tests
- ??
- Profit!
If this PR is succesful I will add the others missing wrappers too. There is also https://github.com/taskforcesh/bullmq/pull/3231, which hasn't added test, but I can also redo with tests.
=> feat(job): Add `getIgnoredChildrenFailures` to the wrapper of sandboxed jobs

python/bullmq/scripts.py, python/bullmq/worker.py, src/classes/scripts.ts, src/classes/worker.ts, src/commands/moveStalledJobsToWait-8.lua, src/commands/moveStalledJobsToWait-9.lua, tests/test_stalled_jobs.ts
1. Why is this change necessary? Now that we have a deferredFailure attribute, we can fail our stalled jobs in a lazy way. So failed event in workers will contain a job instance and not be undefined
=> perf(stalled): fail stalled jobs in a lazy way

python/bullmq/error_code.py, python/bullmq/job.py, python/bullmq/scripts.py, python/bullmq/utils.py, python/tests/job_test.py, python/tests/queue_test.py
1. Why is this change necessary? Stacktrace is being saved on moveToFinished script, also it's a performance change that do not require an extra round trip calling Redis
1. How did you implement this? Use same logic as in node, removing pipe logic
=> fix(job): pass stacktrace into scripts on failures [python]

.github/workflows/release.yml
The GitHub token was not properly passed to the GH cli and therefore the creation of the PR with changelog, etc was failing after a release.
Just pass the GitHub token into the GH_TOKEN variable
=> ci: use GH_TOKEN for GitHub CLI in release workflow

src/classes/job-scheduler.ts, src/classes/scripts.ts, src/commands/includes/storeJobScheduler.lua, src/interfaces/job-scheduler-json.ts, src/interfaces/repeat-options.ts, src/interfaces/repeatable-options.ts, tests/test_job_scheduler.ts, tests/test_job_scheduler_stress.ts
1. Why is this change necessary? Scheduler information is missing offset attribute.
1. How did you implement this? Pass value to be saved in job scheduler hash
=> perf(scheduler): save offset value when every is provided

src/classes/job.ts, src/classes/queue-base.ts, src/classes/scripts.ts, src/classes/worker.ts, src/types/index.ts, src/types/minimal-queue.ts, src/types/script-queue-context.ts, src/utils.ts, tests/test_events.ts
1. Why is this change necessary? Queue instance incluyes scripts instance, but it's also passed as an instance of Scripts
=> fix: avoid circular reference between scripts and queue

src/classes/job-scheduler.ts, tests/test_job_scheduler_stress.ts
1. Why is this change necessary? When calculating delay, there is an opportunity where startMillis + offset is slightly higher than current next slot. As startMillis for subsequent delayed jobs should already contain offset value, we can subtract this value to get a more accurate delay and not skip one iteration
=> fix(scheduler): fix slot calculation when using every

src/classes/worker.ts, src/commands/includes/prepareJobForProcessing.lua, tests/test_rate_limiter.ts
1. Why is this change necessary? We should only wait for the rate limit when there are no more task to process
1. How did you implement this? Only wait for rate limit when needed.
=> perf(worker): do not wait rate limit when fetching jobs

src/classes/worker.ts
=> perf(woker): keep lower blockTimeout when consuming delayed markers

src/classes/worker.ts, tests/test_repeat.ts
1. Why is this change necessary? Legacy format is not respected because is using new job scheduler scripts
1. How did you implement this? Need to validate repeat key that is having the right format in order to use legacy scripts
Fixes https://github.com/taskforcesh/bullmq/issues/3275
=> fix(repeat): use legacy updateRepeatableJob script when old format is present

src/classes/worker.ts, tests/test_worker.ts
1. Why is this change necessary? While pausing or closing a worker, both method wait for pending jobs to be processed before resolving. But we are only taking in count those jobs that are currently active (calling processor method). These jobs that are currently processing can return a new job instance as part of a raise condition where fetch next boolean was set as true when moving these jobs to completed or failed. Job instances being returned will be in active state, so we need to try to process them as well, in these way we are waiting for all jobs (currently processed and pending ones - returned by processors)
1. How did you implement this? Instead of calling waitAll method that only waits for pending methods that could possible return job instances, just keep looping in main while …
=> fix(worker): do not keep active jobs when pausing or closing

package.json, yarn.lock
Updating `eslint` because its using a compromising version of `eslint/plugin-kit`
Modified `eslint` version from `"^9.31.0"` to `"^9.32.0"` in `package.json` then ran
```
yarn install
```
=> ci(deps): update @eslint/plugin-kit to v0.3.4

src/classes/child-processor.ts, src/classes/job.ts, src/classes/sandbox.ts, src/enums/child-command.ts, src/enums/parent-command.ts, src/interfaces/sandboxed-job.ts, src/types/job-json-sandbox.ts, tests/fixtures/fixture_processor_move_to_wait_for_children.js, tests/test_sandboxed_process.ts, yarn.lock
Currently it is impossible to implement https://docs.bullmq.io/patterns/process-step-jobs#waiting-children pattern in sandboxed jobs due to:
- missing `moveToWaitingChildren` method
- missing `queueQualifiedName`
This is built on top of #3231, but adds tests following the waiting for children pattern in the linked documentation.
It fixes #3230
1. Added `queueQualifiedName` and `moveToWaitingChildren` to `SandboxedJob`
2. Implemented a unit test
=> feat(job): Add moveToWaitingChildren to the wrapper of sandboxed jobs

src/classes/queue.ts, tests/test_queue.ts
Fixed by simplifying JobBase to always wrap data types in Job instances
When T = any (default), TypeScript couldn't reliably resolve this to Job<any, any, string>.
```typescript
type JobBase<T, ResultType, NameType extends string> = T extends Job<any, any, any>
? T
: Job<T, ResultType, NameType>;
```
since `any extends Job<any, any, any>` would always true.
Add a check if user T is any, fall back to the Job<any, any, string>
=> fix(queue.ts): preserve Job type inference when no explicit type for JobBase

docs/gitbook/bullmq-pro/changelog.md
Automated update of BullMQ Pro changelog for version v7.38.5
This PR updates the BullMQ Pro changelog with the latest release notes.
=> docs: update bullmq-pro changelog for version v7.38.5

docs/gitbook/bullmq-pro/changelog.md
Automated update of BullMQ Pro changelog for version v7.39.0
This PR updates the BullMQ Pro changelog with the latest release notes.
=> docs: update bullmq-pro changelog for version v7.39.0

docs/gitbook/SUMMARY.md, docs/gitbook/bullmq-pro/changelog.md, docs/gitbook/changelog.md, docs/gitbook/python/changelog.md, docs/gitbook/python/changelogs/changelog-v0.md, docs/gitbook/python/changelogs/changelog-v1.md, package.json, yarn.lock
1. Why is this change necessary? In order to follow our regular semantic-release format as it needs to use conventional-changelog-conventionalcommits preset
=> ci(deps): fix semantic-release format using conventionalcommits

src/classes/queue.ts
The typo could have caused confusion, at least at first glance (I had to do a double take while reading it because it tripped me up). The description of `obliterate` is now a bit clearer on first read.
It's a very, very simple change - just a typo fix.
=> fixed typo in queue obliterate jsdoc comment

docs/gitbook/bullmq-pro/changelog.md
Automated update of BullMQ Pro changelog for version v7.39.2
This PR updates the BullMQ Pro changelog with the latest release notes.
=> docs: update bullmq-pro changelog for version v7.39.2

src/commands/index.ts, src/commands/script-loader.ts, tests/test_script_loader.ts
1. Why is this change necessary? To have same version of scrip loader and also change how base reference is being built, this way pro version do not need to remove script loader tests every time that we updated base package
=> refactor(script-loader): sync with pro version

docs/gitbook/bullmq-pro/changelog.md
Automated update of BullMQ Pro changelog for version v7.39.3
This PR updates the BullMQ Pro changelog with the latest release notes.
=> docs: update bullmq-pro changelog for version v7.39.3
